// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mlkem_accelerator_compress_76_Pipeline_VITIS_LOOP_1590_5 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        s_b_dout,
        s_b_num_data_valid,
        s_b_fifo_cap,
        s_b_empty_n,
        s_b_read,
        s_ct_orig_din,
        s_ct_orig_num_data_valid,
        s_ct_orig_fifo_cap,
        s_ct_orig_full_n,
        s_ct_orig_write
);

parameter    ap_ST_fsm_pp0_stage0 = 8'd1;
parameter    ap_ST_fsm_pp0_stage1 = 8'd2;
parameter    ap_ST_fsm_pp0_stage2 = 8'd4;
parameter    ap_ST_fsm_pp0_stage3 = 8'd8;
parameter    ap_ST_fsm_pp0_stage4 = 8'd16;
parameter    ap_ST_fsm_pp0_stage5 = 8'd32;
parameter    ap_ST_fsm_pp0_stage6 = 8'd64;
parameter    ap_ST_fsm_pp0_stage7 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] s_b_dout;
input  [10:0] s_b_num_data_valid;
input  [10:0] s_b_fifo_cap;
input   s_b_empty_n;
output   s_b_read;
output  [7:0] s_ct_orig_din;
input  [8:0] s_ct_orig_num_data_valid;
input  [8:0] s_ct_orig_fifo_cap;
input   s_ct_orig_full_n;
output   s_ct_orig_write;

reg ap_idle;
reg s_b_read;
reg[7:0] s_ct_orig_din;
reg s_ct_orig_write;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage3;
reg   [0:0] icmp_ln1590_reg_506;
reg    ap_block_state4_pp0_stage3_iter0;
reg    ap_block_state12_pp0_stage3_iter1;
reg    ap_block_pp0_stage3_subdone;
reg    ap_condition_exit_pp0_iter0_stage3;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage7;
reg    ap_block_state8_pp0_stage7_iter0;
reg    ap_block_pp0_stage7_subdone;
reg    s_b_blk_n;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2;
wire    ap_block_pp0_stage3;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_pp0_stage6;
wire    ap_block_pp0_stage7;
wire    ap_block_pp0_stage0;
reg    s_ct_orig_blk_n;
wire   [3:0] grp_fu_84_p4;
reg   [3:0] reg_94;
reg    ap_block_pp0_stage3_11001;
reg    ap_block_state6_pp0_stage5_iter0;
reg    ap_block_pp0_stage5_11001;
reg    ap_block_pp0_stage7_11001;
reg    ap_block_state2_pp0_stage1_iter0;
reg    ap_block_state10_pp0_stage1_iter1;
reg    ap_block_pp0_stage1_11001;
wire   [0:0] icmp_ln1590_fu_106_p2;
reg    ap_block_state9_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [15:0] u_16_fu_139_p2;
reg   [15:0] u_16_reg_510;
wire   [20:0] add_ln1595_fu_156_p2;
reg   [20:0] add_ln1595_reg_515;
reg    ap_block_state3_pp0_stage2_iter0;
reg    ap_block_pp0_stage2_11001;
wire   [15:0] u_18_fu_178_p2;
reg   [15:0] u_18_reg_520;
wire   [20:0] add_ln1595_1_fu_199_p2;
reg   [20:0] add_ln1595_1_reg_525;
wire   [15:0] u_20_fu_221_p2;
reg   [15:0] u_20_reg_530;
wire   [20:0] add_ln1595_2_fu_242_p2;
reg   [20:0] add_ln1595_2_reg_535;
reg    ap_block_state5_pp0_stage4_iter0;
reg    ap_block_pp0_stage4_11001;
wire   [15:0] u_22_fu_264_p2;
reg   [15:0] u_22_reg_540;
wire   [7:0] tmp_160_fu_270_p3;
reg   [7:0] tmp_160_reg_545;
wire   [20:0] add_ln1595_3_fu_293_p2;
reg   [20:0] add_ln1595_3_reg_550;
wire   [15:0] u_24_fu_315_p2;
reg   [15:0] u_24_reg_555;
wire   [20:0] add_ln1595_4_fu_336_p2;
reg   [20:0] add_ln1595_4_reg_560;
reg    ap_block_state7_pp0_stage6_iter0;
reg    ap_block_pp0_stage6_11001;
wire   [15:0] u_26_fu_358_p2;
reg   [15:0] u_26_reg_565;
wire   [7:0] tmp_161_fu_364_p3;
reg   [7:0] tmp_161_reg_570;
wire   [20:0] add_ln1595_5_fu_387_p2;
reg   [20:0] add_ln1595_5_reg_575;
wire   [15:0] u_28_fu_409_p2;
reg   [15:0] u_28_reg_580;
wire   [20:0] add_ln1595_6_fu_430_p2;
reg   [20:0] add_ln1595_6_reg_585;
wire   [15:0] u_30_fu_452_p2;
reg   [15:0] u_30_reg_590;
wire   [7:0] tmp_162_fu_458_p3;
reg   [7:0] tmp_162_reg_595;
wire   [20:0] add_ln1595_7_fu_481_p2;
reg   [20:0] add_ln1595_7_reg_600;
reg   [3:0] trunc_ln1595_6_reg_605;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [5:0] i_124_fu_62;
wire   [5:0] i_195_fu_112_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_i;
reg    ap_block_pp0_stage5_01001;
reg    ap_block_pp0_stage7_01001;
reg    ap_block_pp0_stage1_01001;
wire   [7:0] tmp_163_fu_491_p3;
reg    ap_block_pp0_stage3_01001;
reg   [20:0] grp_fu_79_p0;
wire   [42:0] zext_ln1595_16_fu_184_p1;
wire   [42:0] zext_ln1595_17_fu_227_p1;
wire   [42:0] zext_ln1595_18_fu_278_p1;
wire   [42:0] zext_ln1595_19_fu_321_p1;
wire   [42:0] zext_ln1595_20_fu_372_p1;
wire   [42:0] zext_ln1595_21_fu_415_p1;
wire   [42:0] zext_ln1595_22_fu_466_p1;
wire   [42:0] zext_ln1595_23_fu_487_p1;
wire   [22:0] grp_fu_79_p1;
wire   [42:0] grp_fu_79_p2;
wire   [0:0] tmp_fu_123_p3;
wire   [15:0] select_ln1594_fu_131_p3;
wire   [19:0] shl_ln6_fu_145_p3;
wire   [20:0] zext_ln1595_fu_152_p1;
wire   [0:0] tmp_153_fu_162_p3;
wire   [15:0] select_ln1594_8_fu_170_p3;
wire   [19:0] shl_ln1595_1_fu_188_p3;
wire   [20:0] zext_ln1595_2_fu_195_p1;
wire   [0:0] tmp_154_fu_205_p3;
wire   [15:0] select_ln1594_9_fu_213_p3;
wire   [19:0] shl_ln1595_2_fu_231_p3;
wire   [20:0] zext_ln1595_4_fu_238_p1;
wire   [0:0] tmp_155_fu_248_p3;
wire   [15:0] select_ln1594_10_fu_256_p3;
wire   [19:0] shl_ln1595_3_fu_282_p3;
wire   [20:0] zext_ln1595_6_fu_289_p1;
wire   [0:0] tmp_156_fu_299_p3;
wire   [15:0] select_ln1594_11_fu_307_p3;
wire   [19:0] shl_ln1595_4_fu_325_p3;
wire   [20:0] zext_ln1595_8_fu_332_p1;
wire   [0:0] tmp_157_fu_342_p3;
wire   [15:0] select_ln1594_12_fu_350_p3;
wire   [19:0] shl_ln1595_5_fu_376_p3;
wire   [20:0] zext_ln1595_10_fu_383_p1;
wire   [0:0] tmp_158_fu_393_p3;
wire   [15:0] select_ln1594_13_fu_401_p3;
wire   [19:0] shl_ln1595_6_fu_419_p3;
wire   [20:0] zext_ln1595_12_fu_426_p1;
wire   [0:0] tmp_159_fu_436_p3;
wire   [15:0] select_ln1594_14_fu_444_p3;
wire   [19:0] shl_ln1595_7_fu_470_p3;
wire   [20:0] zext_ln1595_14_fu_477_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [7:0] ap_NS_fsm;
reg    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
reg    ap_block_pp0_stage1_subdone;
reg    ap_block_pp0_stage2_subdone;
reg    ap_block_pp0_stage4_subdone;
reg    ap_block_pp0_stage5_subdone;
reg    ap_block_pp0_stage6_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 i_124_fu_62 = 6'd0;
#0 ap_done_reg = 1'b0;
end

mlkem_accelerator_mul_21ns_23ns_43_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 21 ),
    .din1_WIDTH( 23 ),
    .dout_WIDTH( 43 ))
mul_21ns_23ns_43_1_1_U1766(
    .din0(grp_fu_79_p0),
    .din1(grp_fu_79_p1),
    .dout(grp_fu_79_p2)
);

mlkem_accelerator_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage3),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage3)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln1590_fu_106_p2 == 1'd0))) begin
            i_124_fu_62 <= i_195_fu_112_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_124_fu_62 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        add_ln1595_1_reg_525[20 : 4] <= add_ln1595_1_fu_199_p2[20 : 4];
        u_20_reg_530 <= u_20_fu_221_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        add_ln1595_2_reg_535[20 : 4] <= add_ln1595_2_fu_242_p2[20 : 4];
        tmp_160_reg_545 <= tmp_160_fu_270_p3;
        u_22_reg_540 <= u_22_fu_264_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        add_ln1595_3_reg_550[20 : 4] <= add_ln1595_3_fu_293_p2[20 : 4];
        u_24_reg_555 <= u_24_fu_315_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        add_ln1595_4_reg_560[20 : 4] <= add_ln1595_4_fu_336_p2[20 : 4];
        tmp_161_reg_570 <= tmp_161_fu_364_p3;
        u_26_reg_565 <= u_26_fu_358_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        add_ln1595_5_reg_575[20 : 4] <= add_ln1595_5_fu_387_p2[20 : 4];
        u_28_reg_580 <= u_28_fu_409_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln1595_6_reg_585[20 : 4] <= add_ln1595_6_fu_430_p2[20 : 4];
        icmp_ln1590_reg_506 <= icmp_ln1590_fu_106_p2;
        tmp_162_reg_595 <= tmp_162_fu_458_p3;
        u_30_reg_590 <= u_30_fu_452_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln1595_7_reg_600[20 : 4] <= add_ln1595_7_fu_481_p2[20 : 4];
        u_16_reg_510 <= u_16_fu_139_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add_ln1595_reg_515[20 : 4] <= add_ln1595_fu_156_p2[20 : 4];
        u_18_reg_520 <= u_18_fu_178_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        reg_94 <= {{grp_fu_79_p2[36:33]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        trunc_ln1595_6_reg_605 <= {{grp_fu_79_p2[36:33]}};
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_subdone) & (icmp_ln1590_reg_506 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage7_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i = 6'd0;
    end else begin
        ap_sig_allocacmp_i = i_124_fu_62;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_79_p0 = zext_ln1595_23_fu_487_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_79_p0 = zext_ln1595_22_fu_466_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_79_p0 = zext_ln1595_21_fu_415_p1;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_fu_79_p0 = zext_ln1595_20_fu_372_p1;
    end else if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_fu_79_p0 = zext_ln1595_19_fu_321_p1;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_79_p0 = zext_ln1595_18_fu_278_p1;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_79_p0 = zext_ln1595_17_fu_227_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_79_p0 = zext_ln1595_16_fu_184_p1;
    end else begin
        grp_fu_79_p0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage7) & (icmp_ln1590_reg_506 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6) & (icmp_ln1590_reg_506 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5) & (icmp_ln1590_reg_506 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4) & (icmp_ln1590_reg_506 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3) & (icmp_ln1590_reg_506 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2) & (icmp_ln1590_reg_506 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1) & (icmp_ln1590_reg_506 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        s_b_blk_n = s_b_empty_n;
    end else begin
        s_b_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage6_11001) & (icmp_ln1590_reg_506 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage4_11001) & (icmp_ln1590_reg_506 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln1590_reg_506 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln1590_reg_506 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage7_11001) & (icmp_ln1590_reg_506 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage5_11001) & (icmp_ln1590_reg_506 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage3_11001) & (icmp_ln1590_reg_506 == 1'd0) 
    & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        s_b_read = 1'b1;
    end else begin
        s_b_read = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage7) & (icmp_ln1590_reg_506 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage5) & (icmp_ln1590_reg_506 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        s_ct_orig_blk_n = s_ct_orig_full_n;
    end else begin
        s_ct_orig_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        s_ct_orig_din = tmp_163_fu_491_p3;
    end else if (((1'b0 == ap_block_pp0_stage1_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        s_ct_orig_din = tmp_162_reg_595;
    end else if (((1'b0 == ap_block_pp0_stage7_01001) & (icmp_ln1590_reg_506 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        s_ct_orig_din = tmp_161_reg_570;
    end else if (((1'b0 == ap_block_pp0_stage5_01001) & (icmp_ln1590_reg_506 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        s_ct_orig_din = tmp_160_reg_545;
    end else begin
        s_ct_orig_din = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage7_11001) & (icmp_ln1590_reg_506 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage5_11001) & (icmp_ln1590_reg_506 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        s_ct_orig_write = 1'b1;
    end else begin
        s_ct_orig_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage3)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1595_1_fu_199_p2 = (zext_ln1595_2_fu_195_p1 + 21'd1664);

assign add_ln1595_2_fu_242_p2 = (zext_ln1595_4_fu_238_p1 + 21'd1664);

assign add_ln1595_3_fu_293_p2 = (zext_ln1595_6_fu_289_p1 + 21'd1664);

assign add_ln1595_4_fu_336_p2 = (zext_ln1595_8_fu_332_p1 + 21'd1664);

assign add_ln1595_5_fu_387_p2 = (zext_ln1595_10_fu_383_p1 + 21'd1664);

assign add_ln1595_6_fu_430_p2 = (zext_ln1595_12_fu_426_p1 + 21'd1664);

assign add_ln1595_7_fu_481_p2 = (zext_ln1595_14_fu_477_p1 + 21'd1664);

assign add_ln1595_fu_156_p2 = (zext_ln1595_fu_152_p1 + 21'd1664);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state9_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state9_pp0_stage0_iter1));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage1_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage1_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage1_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0)));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage2_iter0));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage2_iter0));
end

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_01001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage3_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage3_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage3_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage3_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage3_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage3_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage3_iter0)));
end

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage4_iter0));
end

always @ (*) begin
    ap_block_pp0_stage4_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage4_iter0));
end

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage5_01001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage5_iter0));
end

always @ (*) begin
    ap_block_pp0_stage5_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage5_iter0));
end

always @ (*) begin
    ap_block_pp0_stage5_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage5_iter0));
end

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage6_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage6_iter0));
end

always @ (*) begin
    ap_block_pp0_stage6_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage6_iter0));
end

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage7_01001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state8_pp0_stage7_iter0));
end

always @ (*) begin
    ap_block_pp0_stage7_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state8_pp0_stage7_iter0));
end

always @ (*) begin
    ap_block_pp0_stage7_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state8_pp0_stage7_iter0));
end

always @ (*) begin
    ap_block_state10_pp0_stage1_iter1 = (s_ct_orig_full_n == 1'b0);
end

always @ (*) begin
    ap_block_state12_pp0_stage3_iter1 = (s_ct_orig_full_n == 1'b0);
end

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0 = ((icmp_ln1590_reg_506 == 1'd0) & (s_b_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage2_iter0 = ((icmp_ln1590_reg_506 == 1'd0) & (s_b_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage3_iter0 = ((icmp_ln1590_reg_506 == 1'd0) & (s_b_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state5_pp0_stage4_iter0 = ((icmp_ln1590_reg_506 == 1'd0) & (s_b_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state6_pp0_stage5_iter0 = (((s_ct_orig_full_n == 1'b0) & (icmp_ln1590_reg_506 == 1'd0)) | ((icmp_ln1590_reg_506 == 1'd0) & (s_b_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state7_pp0_stage6_iter0 = ((icmp_ln1590_reg_506 == 1'd0) & (s_b_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state8_pp0_stage7_iter0 = (((s_ct_orig_full_n == 1'b0) & (icmp_ln1590_reg_506 == 1'd0)) | ((icmp_ln1590_reg_506 == 1'd0) & (s_b_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state9_pp0_stage0_iter1 = (s_b_empty_n == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage3;

assign grp_fu_79_p1 = 43'd2580335;

assign grp_fu_84_p4 = {{grp_fu_79_p2[36:33]}};

assign i_195_fu_112_p2 = (ap_sig_allocacmp_i + 6'd1);

assign icmp_ln1590_fu_106_p2 = ((ap_sig_allocacmp_i == 6'd32) ? 1'b1 : 1'b0);

assign select_ln1594_10_fu_256_p3 = ((tmp_155_fu_248_p3[0:0] == 1'b1) ? 16'd3329 : 16'd0);

assign select_ln1594_11_fu_307_p3 = ((tmp_156_fu_299_p3[0:0] == 1'b1) ? 16'd3329 : 16'd0);

assign select_ln1594_12_fu_350_p3 = ((tmp_157_fu_342_p3[0:0] == 1'b1) ? 16'd3329 : 16'd0);

assign select_ln1594_13_fu_401_p3 = ((tmp_158_fu_393_p3[0:0] == 1'b1) ? 16'd3329 : 16'd0);

assign select_ln1594_14_fu_444_p3 = ((tmp_159_fu_436_p3[0:0] == 1'b1) ? 16'd3329 : 16'd0);

assign select_ln1594_8_fu_170_p3 = ((tmp_153_fu_162_p3[0:0] == 1'b1) ? 16'd3329 : 16'd0);

assign select_ln1594_9_fu_213_p3 = ((tmp_154_fu_205_p3[0:0] == 1'b1) ? 16'd3329 : 16'd0);

assign select_ln1594_fu_131_p3 = ((tmp_fu_123_p3[0:0] == 1'b1) ? 16'd3329 : 16'd0);

assign shl_ln1595_1_fu_188_p3 = {{u_18_reg_520}, {4'd0}};

assign shl_ln1595_2_fu_231_p3 = {{u_20_reg_530}, {4'd0}};

assign shl_ln1595_3_fu_282_p3 = {{u_22_reg_540}, {4'd0}};

assign shl_ln1595_4_fu_325_p3 = {{u_24_reg_555}, {4'd0}};

assign shl_ln1595_5_fu_376_p3 = {{u_26_reg_565}, {4'd0}};

assign shl_ln1595_6_fu_419_p3 = {{u_28_reg_580}, {4'd0}};

assign shl_ln1595_7_fu_470_p3 = {{u_30_reg_590}, {4'd0}};

assign shl_ln6_fu_145_p3 = {{u_16_reg_510}, {4'd0}};

assign tmp_153_fu_162_p3 = s_b_dout[32'd15];

assign tmp_154_fu_205_p3 = s_b_dout[32'd15];

assign tmp_155_fu_248_p3 = s_b_dout[32'd15];

assign tmp_156_fu_299_p3 = s_b_dout[32'd15];

assign tmp_157_fu_342_p3 = s_b_dout[32'd15];

assign tmp_158_fu_393_p3 = s_b_dout[32'd15];

assign tmp_159_fu_436_p3 = s_b_dout[32'd15];

assign tmp_160_fu_270_p3 = {{grp_fu_84_p4}, {reg_94}};

assign tmp_161_fu_364_p3 = {{grp_fu_84_p4}, {reg_94}};

assign tmp_162_fu_458_p3 = {{grp_fu_84_p4}, {reg_94}};

assign tmp_163_fu_491_p3 = {{trunc_ln1595_6_reg_605}, {reg_94}};

assign tmp_fu_123_p3 = s_b_dout[32'd15];

assign u_16_fu_139_p2 = (s_b_dout + select_ln1594_fu_131_p3);

assign u_18_fu_178_p2 = (s_b_dout + select_ln1594_8_fu_170_p3);

assign u_20_fu_221_p2 = (s_b_dout + select_ln1594_9_fu_213_p3);

assign u_22_fu_264_p2 = (s_b_dout + select_ln1594_10_fu_256_p3);

assign u_24_fu_315_p2 = (s_b_dout + select_ln1594_11_fu_307_p3);

assign u_26_fu_358_p2 = (s_b_dout + select_ln1594_12_fu_350_p3);

assign u_28_fu_409_p2 = (s_b_dout + select_ln1594_13_fu_401_p3);

assign u_30_fu_452_p2 = (s_b_dout + select_ln1594_14_fu_444_p3);

assign zext_ln1595_10_fu_383_p1 = shl_ln1595_5_fu_376_p3;

assign zext_ln1595_12_fu_426_p1 = shl_ln1595_6_fu_419_p3;

assign zext_ln1595_14_fu_477_p1 = shl_ln1595_7_fu_470_p3;

assign zext_ln1595_16_fu_184_p1 = add_ln1595_reg_515;

assign zext_ln1595_17_fu_227_p1 = add_ln1595_1_reg_525;

assign zext_ln1595_18_fu_278_p1 = add_ln1595_2_reg_535;

assign zext_ln1595_19_fu_321_p1 = add_ln1595_3_reg_550;

assign zext_ln1595_20_fu_372_p1 = add_ln1595_4_reg_560;

assign zext_ln1595_21_fu_415_p1 = add_ln1595_5_reg_575;

assign zext_ln1595_22_fu_466_p1 = add_ln1595_6_reg_585;

assign zext_ln1595_23_fu_487_p1 = add_ln1595_7_reg_600;

assign zext_ln1595_2_fu_195_p1 = shl_ln1595_1_fu_188_p3;

assign zext_ln1595_4_fu_238_p1 = shl_ln1595_2_fu_231_p3;

assign zext_ln1595_6_fu_289_p1 = shl_ln1595_3_fu_282_p3;

assign zext_ln1595_8_fu_332_p1 = shl_ln1595_4_fu_325_p3;

assign zext_ln1595_fu_152_p1 = shl_ln6_fu_145_p3;

always @ (posedge ap_clk) begin
    add_ln1595_reg_515[3:0] <= 4'b0000;
    add_ln1595_1_reg_525[3:0] <= 4'b0000;
    add_ln1595_2_reg_535[3:0] <= 4'b0000;
    add_ln1595_3_reg_550[3:0] <= 4'b0000;
    add_ln1595_4_reg_560[3:0] <= 4'b0000;
    add_ln1595_5_reg_575[3:0] <= 4'b0000;
    add_ln1595_6_reg_585[3:0] <= 4'b0000;
    add_ln1595_7_reg_600[3:0] <= 4'b0000;
end

endmodule //mlkem_accelerator_compress_76_Pipeline_VITIS_LOOP_1590_5
