// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mlkem_accelerator_cmov (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        s_fail_dout,
        s_fail_num_data_valid,
        s_fail_fifo_cap,
        s_fail_empty_n,
        s_fail_read,
        s_krl_1_dout,
        s_krl_1_num_data_valid,
        s_krl_1_fifo_cap,
        s_krl_1_empty_n,
        s_krl_1_read,
        s_ss_dout,
        s_ss_num_data_valid,
        s_ss_fifo_cap,
        s_ss_empty_n,
        s_ss_read,
        s_ss_mov_din,
        s_ss_mov_num_data_valid,
        s_ss_mov_fifo_cap,
        s_ss_mov_full_n,
        s_ss_mov_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] s_fail_dout;
input  [8:0] s_fail_num_data_valid;
input  [8:0] s_fail_fifo_cap;
input   s_fail_empty_n;
output   s_fail_read;
input  [7:0] s_krl_1_dout;
input  [7:0] s_krl_1_num_data_valid;
input  [7:0] s_krl_1_fifo_cap;
input   s_krl_1_empty_n;
output   s_krl_1_read;
input  [7:0] s_ss_dout;
input  [8:0] s_ss_num_data_valid;
input  [8:0] s_ss_fifo_cap;
input   s_ss_empty_n;
output   s_ss_read;
output  [7:0] s_ss_mov_din;
input  [8:0] s_ss_mov_num_data_valid;
input  [8:0] s_ss_mov_fifo_cap;
input   s_ss_mov_full_n;
output   s_ss_mov_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg s_fail_read;
reg s_krl_1_read;
reg s_ss_read;
reg s_ss_mov_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    s_fail_blk_n;
wire   [7:0] trunc_ln1652_fu_43_p1;
reg   [7:0] trunc_ln1652_reg_53;
reg    ap_block_state1;
wire   [7:0] b_fu_47_p2;
reg   [7:0] b_reg_58;
wire    ap_CS_fsm_state2;
wire    grp_cmov_Pipeline_VITIS_LOOP_1653_2_fu_32_ap_start;
wire    grp_cmov_Pipeline_VITIS_LOOP_1653_2_fu_32_ap_done;
wire    grp_cmov_Pipeline_VITIS_LOOP_1653_2_fu_32_ap_idle;
wire    grp_cmov_Pipeline_VITIS_LOOP_1653_2_fu_32_ap_ready;
wire    grp_cmov_Pipeline_VITIS_LOOP_1653_2_fu_32_s_krl_1_read;
wire    grp_cmov_Pipeline_VITIS_LOOP_1653_2_fu_32_s_ss_read;
wire   [7:0] grp_cmov_Pipeline_VITIS_LOOP_1653_2_fu_32_s_ss_mov_din;
wire    grp_cmov_Pipeline_VITIS_LOOP_1653_2_fu_32_s_ss_mov_write;
reg    grp_cmov_Pipeline_VITIS_LOOP_1653_2_fu_32_ap_start_reg;
wire    ap_CS_fsm_state3;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_cmov_Pipeline_VITIS_LOOP_1653_2_fu_32_ap_start_reg = 1'b0;
end

mlkem_accelerator_cmov_Pipeline_VITIS_LOOP_1653_2 grp_cmov_Pipeline_VITIS_LOOP_1653_2_fu_32(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_cmov_Pipeline_VITIS_LOOP_1653_2_fu_32_ap_start),
    .ap_done(grp_cmov_Pipeline_VITIS_LOOP_1653_2_fu_32_ap_done),
    .ap_idle(grp_cmov_Pipeline_VITIS_LOOP_1653_2_fu_32_ap_idle),
    .ap_ready(grp_cmov_Pipeline_VITIS_LOOP_1653_2_fu_32_ap_ready),
    .s_krl_1_dout(s_krl_1_dout),
    .s_krl_1_num_data_valid(8'd0),
    .s_krl_1_fifo_cap(8'd0),
    .s_krl_1_empty_n(s_krl_1_empty_n),
    .s_krl_1_read(grp_cmov_Pipeline_VITIS_LOOP_1653_2_fu_32_s_krl_1_read),
    .s_ss_dout(s_ss_dout),
    .s_ss_num_data_valid(9'd0),
    .s_ss_fifo_cap(9'd0),
    .s_ss_empty_n(s_ss_empty_n),
    .s_ss_read(grp_cmov_Pipeline_VITIS_LOOP_1653_2_fu_32_s_ss_read),
    .s_ss_mov_din(grp_cmov_Pipeline_VITIS_LOOP_1653_2_fu_32_s_ss_mov_din),
    .s_ss_mov_num_data_valid(9'd0),
    .s_ss_mov_fifo_cap(9'd0),
    .s_ss_mov_full_n(s_ss_mov_full_n),
    .s_ss_mov_write(grp_cmov_Pipeline_VITIS_LOOP_1653_2_fu_32_s_ss_mov_write),
    .b(b_reg_58)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_cmov_Pipeline_VITIS_LOOP_1653_2_fu_32_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_cmov_Pipeline_VITIS_LOOP_1653_2_fu_32_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_cmov_Pipeline_VITIS_LOOP_1653_2_fu_32_ap_start_reg <= 1'b1;
        end else if ((grp_cmov_Pipeline_VITIS_LOOP_1653_2_fu_32_ap_ready == 1'b1)) begin
            grp_cmov_Pipeline_VITIS_LOOP_1653_2_fu_32_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        b_reg_58 <= b_fu_47_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        trunc_ln1652_reg_53 <= trunc_ln1652_fu_43_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_cmov_Pipeline_VITIS_LOOP_1653_2_fu_32_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_cmov_Pipeline_VITIS_LOOP_1653_2_fu_32_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_cmov_Pipeline_VITIS_LOOP_1653_2_fu_32_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        s_fail_blk_n = s_fail_empty_n;
    end else begin
        s_fail_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        s_fail_read = 1'b1;
    end else begin
        s_fail_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        s_krl_1_read = grp_cmov_Pipeline_VITIS_LOOP_1653_2_fu_32_s_krl_1_read;
    end else begin
        s_krl_1_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        s_ss_mov_write = grp_cmov_Pipeline_VITIS_LOOP_1653_2_fu_32_s_ss_mov_write;
    end else begin
        s_ss_mov_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        s_ss_read = grp_cmov_Pipeline_VITIS_LOOP_1653_2_fu_32_s_ss_read;
    end else begin
        s_ss_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_cmov_Pipeline_VITIS_LOOP_1653_2_fu_32_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (s_fail_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign b_fu_47_p2 = (8'd0 - trunc_ln1652_reg_53);

assign grp_cmov_Pipeline_VITIS_LOOP_1653_2_fu_32_ap_start = grp_cmov_Pipeline_VITIS_LOOP_1653_2_fu_32_ap_start_reg;

assign s_ss_mov_din = grp_cmov_Pipeline_VITIS_LOOP_1653_2_fu_32_s_ss_mov_din;

assign trunc_ln1652_fu_43_p1 = s_fail_dout[7:0];

endmodule //mlkem_accelerator_cmov
