// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mlkem_accelerator_rkprf_Pipeline_VITIS_LOOP_777_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        s_kr_ver_dout,
        s_kr_ver_num_data_valid,
        s_kr_ver_fifo_cap,
        s_kr_ver_empty_n,
        s_kr_ver_read,
        s_out_i,
        s_out_o,
        s_out_o_ap_vld,
        s_31_out_i,
        s_31_out_o,
        s_31_out_o_ap_vld,
        s_32_out_i,
        s_32_out_o,
        s_32_out_o_ap_vld,
        s_33_out_i,
        s_33_out_o,
        s_33_out_o_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] s_kr_ver_dout;
input  [8:0] s_kr_ver_num_data_valid;
input  [8:0] s_kr_ver_fifo_cap;
input   s_kr_ver_empty_n;
output   s_kr_ver_read;
input  [63:0] s_out_i;
output  [63:0] s_out_o;
output   s_out_o_ap_vld;
input  [63:0] s_31_out_i;
output  [63:0] s_31_out_o;
output   s_31_out_o_ap_vld;
input  [63:0] s_32_out_i;
output  [63:0] s_32_out_o;
output   s_32_out_o_ap_vld;
input  [63:0] s_33_out_i;
output  [63:0] s_33_out_o;
output   s_33_out_o_ap_vld;

reg ap_idle;
reg s_kr_ver_read;
reg[63:0] s_out_o;
reg s_out_o_ap_vld;
reg[63:0] s_31_out_o;
reg s_31_out_o_ap_vld;
reg[63:0] s_32_out_o;
reg s_32_out_o_ap_vld;
reg[63:0] s_33_out_o;
reg s_33_out_o_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln777_fu_104_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    s_kr_ver_blk_n;
wire    ap_block_pp0_stage0;
reg   [5:0] i_51_reg_225;
reg    ap_block_pp0_stage0_11001;
reg   [5:0] i_51_reg_225_pp0_iter1_reg;
reg   [7:0] s_kr_ver_read_reg_235;
wire   [63:0] xor_ln778_fu_188_p2;
wire   [1:0] trunc_ln778_1_fu_155_p4;
wire    ap_loop_init;
reg   [5:0] i_fu_62;
wire   [5:0] i_52_fu_110_p2;
reg   [5:0] ap_sig_allocacmp_i_51;
wire   [5:0] shl_ln778_1_fu_140_p2;
wire   [63:0] zext_ln778_fu_137_p1;
wire   [63:0] zext_ln778_1_fu_145_p1;
wire   [63:0] tmp_i_fu_164_p9;
wire   [1:0] tmp_i_fu_164_p10;
wire   [63:0] shl_ln778_fu_149_p2;
wire   [63:0] tmp_i_fu_164_p11;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [1:0] tmp_i_fu_164_p1;
wire   [1:0] tmp_i_fu_164_p3;
wire  signed [1:0] tmp_i_fu_164_p5;
wire  signed [1:0] tmp_i_fu_164_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 i_fu_62 = 6'd0;
#0 ap_done_reg = 1'b0;
end

mlkem_accelerator_sparsemux_9_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 64 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_9_2_64_1_1_U1102(
    .din0(s_33_out_i),
    .din1(s_32_out_i),
    .din2(s_31_out_i),
    .din3(s_out_i),
    .def(tmp_i_fu_164_p9),
    .sel(tmp_i_fu_164_p10),
    .dout(tmp_i_fu_164_p11)
);

mlkem_accelerator_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln777_fu_104_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_62 <= i_52_fu_110_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_62 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        i_51_reg_225 <= ap_sig_allocacmp_i_51;
        i_51_reg_225_pp0_iter1_reg <= i_51_reg_225;
        s_kr_ver_read_reg_235 <= s_kr_ver_dout;
    end
end

always @ (*) begin
    if (((icmp_ln777_fu_104_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_51 = 6'd0;
    end else begin
        ap_sig_allocacmp_i_51 = i_fu_62;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            s_31_out_o = 64'd0;
        end else if (((trunc_ln778_1_fu_155_p4 == 2'd2) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            s_31_out_o = xor_ln778_fu_188_p2;
        end else begin
            s_31_out_o = s_31_out_i;
        end
    end else begin
        s_31_out_o = s_31_out_i;
    end
end

always @ (*) begin
    if ((((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((trunc_ln778_1_fu_155_p4 == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        s_31_out_o_ap_vld = 1'b1;
    end else begin
        s_31_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            s_32_out_o = 64'd0;
        end else if (((trunc_ln778_1_fu_155_p4 == 2'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            s_32_out_o = xor_ln778_fu_188_p2;
        end else begin
            s_32_out_o = s_32_out_i;
        end
    end else begin
        s_32_out_o = s_32_out_i;
    end
end

always @ (*) begin
    if ((((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((trunc_ln778_1_fu_155_p4 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        s_32_out_o_ap_vld = 1'b1;
    end else begin
        s_32_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            s_33_out_o = 64'd0;
        end else if (((trunc_ln778_1_fu_155_p4 == 2'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            s_33_out_o = xor_ln778_fu_188_p2;
        end else begin
            s_33_out_o = s_33_out_i;
        end
    end else begin
        s_33_out_o = s_33_out_i;
    end
end

always @ (*) begin
    if ((((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((trunc_ln778_1_fu_155_p4 == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        s_33_out_o_ap_vld = 1'b1;
    end else begin
        s_33_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_kr_ver_blk_n = s_kr_ver_empty_n;
    end else begin
        s_kr_ver_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_kr_ver_read = 1'b1;
    end else begin
        s_kr_ver_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            s_out_o = 64'd0;
        end else if (((trunc_ln778_1_fu_155_p4 == 2'd3) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            s_out_o = xor_ln778_fu_188_p2;
        end else begin
            s_out_o = s_out_i;
        end
    end else begin
        s_out_o = s_out_i;
    end
end

always @ (*) begin
    if ((((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((trunc_ln778_1_fu_155_p4 == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        s_out_o_ap_vld = 1'b1;
    end else begin
        s_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (s_kr_ver_empty_n == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign i_52_fu_110_p2 = (ap_sig_allocacmp_i_51 + 6'd1);

assign icmp_ln777_fu_104_p2 = ((ap_sig_allocacmp_i_51 == 6'd32) ? 1'b1 : 1'b0);

assign shl_ln778_1_fu_140_p2 = i_51_reg_225_pp0_iter1_reg << 6'd3;

assign shl_ln778_fu_149_p2 = zext_ln778_fu_137_p1 << zext_ln778_1_fu_145_p1;

assign tmp_i_fu_164_p10 = {{i_51_reg_225_pp0_iter1_reg[4:3]}};

assign tmp_i_fu_164_p9 = 'bx;

assign trunc_ln778_1_fu_155_p4 = {{i_51_reg_225_pp0_iter1_reg[4:3]}};

assign xor_ln778_fu_188_p2 = (tmp_i_fu_164_p11 ^ shl_ln778_fu_149_p2);

assign zext_ln778_1_fu_145_p1 = shl_ln778_1_fu_140_p2;

assign zext_ln778_fu_137_p1 = s_kr_ver_read_reg_235;

endmodule //mlkem_accelerator_rkprf_Pipeline_VITIS_LOOP_777_3
