// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mlkem_accelerator_verify (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        s_ct_1_dout,
        s_ct_1_num_data_valid,
        s_ct_1_fifo_cap,
        s_ct_1_empty_n,
        s_ct_1_read,
        s_cmp_dout,
        s_cmp_num_data_valid,
        s_cmp_fifo_cap,
        s_cmp_empty_n,
        s_cmp_read,
        s_fail_din,
        s_fail_num_data_valid,
        s_fail_fifo_cap,
        s_fail_full_n,
        s_fail_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [7:0] s_ct_1_dout;
input  [14:0] s_ct_1_num_data_valid;
input  [14:0] s_ct_1_fifo_cap;
input   s_ct_1_empty_n;
output   s_ct_1_read;
input  [7:0] s_cmp_dout;
input  [12:0] s_cmp_num_data_valid;
input  [12:0] s_cmp_fifo_cap;
input   s_cmp_empty_n;
output   s_cmp_read;
output  [31:0] s_fail_din;
input  [8:0] s_fail_num_data_valid;
input  [8:0] s_fail_fifo_cap;
input   s_fail_full_n;
output   s_fail_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg s_ct_1_read;
reg s_cmp_read;
reg s_fail_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    s_fail_blk_n;
wire    ap_CS_fsm_state3;
wire    grp_verify_Pipeline_VITIS_LOOP_1639_2_fu_41_ap_start;
wire    grp_verify_Pipeline_VITIS_LOOP_1639_2_fu_41_ap_done;
wire    grp_verify_Pipeline_VITIS_LOOP_1639_2_fu_41_ap_idle;
wire    grp_verify_Pipeline_VITIS_LOOP_1639_2_fu_41_ap_ready;
wire    grp_verify_Pipeline_VITIS_LOOP_1639_2_fu_41_s_ct_1_read;
wire    grp_verify_Pipeline_VITIS_LOOP_1639_2_fu_41_s_cmp_read;
wire   [7:0] grp_verify_Pipeline_VITIS_LOOP_1639_2_fu_41_r_out;
wire    grp_verify_Pipeline_VITIS_LOOP_1639_2_fu_41_r_out_ap_vld;
reg    grp_verify_Pipeline_VITIS_LOOP_1639_2_fu_41_ap_start_reg;
reg    ap_block_state1_ignore_call14;
wire    ap_CS_fsm_state2;
wire   [8:0] zext_ln1642_fu_53_p1;
wire   [8:0] sub_ln1642_fu_57_p2;
wire   [0:0] tmp_fu_63_p3;
reg   [2:0] ap_NS_fsm;
reg    ap_block_state1;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_verify_Pipeline_VITIS_LOOP_1639_2_fu_41_ap_start_reg = 1'b0;
end

mlkem_accelerator_verify_Pipeline_VITIS_LOOP_1639_2 grp_verify_Pipeline_VITIS_LOOP_1639_2_fu_41(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_verify_Pipeline_VITIS_LOOP_1639_2_fu_41_ap_start),
    .ap_done(grp_verify_Pipeline_VITIS_LOOP_1639_2_fu_41_ap_done),
    .ap_idle(grp_verify_Pipeline_VITIS_LOOP_1639_2_fu_41_ap_idle),
    .ap_ready(grp_verify_Pipeline_VITIS_LOOP_1639_2_fu_41_ap_ready),
    .s_ct_1_dout(s_ct_1_dout),
    .s_ct_1_num_data_valid(15'd0),
    .s_ct_1_fifo_cap(15'd0),
    .s_ct_1_empty_n(s_ct_1_empty_n),
    .s_ct_1_read(grp_verify_Pipeline_VITIS_LOOP_1639_2_fu_41_s_ct_1_read),
    .s_cmp_dout(s_cmp_dout),
    .s_cmp_num_data_valid(13'd0),
    .s_cmp_fifo_cap(13'd0),
    .s_cmp_empty_n(s_cmp_empty_n),
    .s_cmp_read(grp_verify_Pipeline_VITIS_LOOP_1639_2_fu_41_s_cmp_read),
    .r_out(grp_verify_Pipeline_VITIS_LOOP_1639_2_fu_41_r_out),
    .r_out_ap_vld(grp_verify_Pipeline_VITIS_LOOP_1639_2_fu_41_r_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((s_fail_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_verify_Pipeline_VITIS_LOOP_1639_2_fu_41_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state1_ignore_call14) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_verify_Pipeline_VITIS_LOOP_1639_2_fu_41_ap_start_reg <= 1'b1;
        end else if ((grp_verify_Pipeline_VITIS_LOOP_1639_2_fu_41_ap_ready == 1'b1)) begin
            grp_verify_Pipeline_VITIS_LOOP_1639_2_fu_41_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_verify_Pipeline_VITIS_LOOP_1639_2_fu_41_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((s_fail_full_n == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((s_fail_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((s_fail_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        s_cmp_read = grp_verify_Pipeline_VITIS_LOOP_1639_2_fu_41_s_cmp_read;
    end else begin
        s_cmp_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        s_ct_1_read = grp_verify_Pipeline_VITIS_LOOP_1639_2_fu_41_s_ct_1_read;
    end else begin
        s_ct_1_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        s_fail_blk_n = s_fail_full_n;
    end else begin
        s_fail_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((s_fail_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        s_fail_write = 1'b1;
    end else begin
        s_fail_write = 1'b0;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_verify_Pipeline_VITIS_LOOP_1639_2_fu_41_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((s_fail_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call14 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign grp_verify_Pipeline_VITIS_LOOP_1639_2_fu_41_ap_start = grp_verify_Pipeline_VITIS_LOOP_1639_2_fu_41_ap_start_reg;

assign s_fail_din = tmp_fu_63_p3;

assign start_out = real_start;

assign sub_ln1642_fu_57_p2 = (9'd0 - zext_ln1642_fu_53_p1);

assign tmp_fu_63_p3 = sub_ln1642_fu_57_p2[32'd8];

assign zext_ln1642_fu_53_p1 = grp_verify_Pipeline_VITIS_LOOP_1639_2_fu_41_r_out;

endmodule //mlkem_accelerator_verify
