// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mlkem_accelerator_unpack_60 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        s_pk_dout,
        s_pk_num_data_valid,
        s_pk_fifo_cap,
        s_pk_empty_n,
        s_pk_read,
        s_pkpv_din,
        s_pkpv_num_data_valid,
        s_pkpv_fifo_cap,
        s_pkpv_full_n,
        s_pkpv_write,
        s_seed_din,
        s_seed_num_data_valid,
        s_seed_fifo_cap,
        s_seed_full_n,
        s_seed_write
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [7:0] s_pk_dout;
input  [8:0] s_pk_num_data_valid;
input  [8:0] s_pk_fifo_cap;
input   s_pk_empty_n;
output   s_pk_read;
output  [15:0] s_pkpv_din;
input  [12:0] s_pkpv_num_data_valid;
input  [12:0] s_pkpv_fifo_cap;
input   s_pkpv_full_n;
output   s_pkpv_write;
output  [255:0] s_seed_din;
input  [2:0] s_seed_num_data_valid;
input  [2:0] s_seed_fifo_cap;
input   s_seed_full_n;
output   s_seed_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg s_pk_read;
reg s_pkpv_write;
reg s_seed_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    s_seed_blk_n;
wire    ap_CS_fsm_state6;
wire    grp_unpack_60_Pipeline_VITIS_LOOP_1099_2_fu_37_ap_start;
wire    grp_unpack_60_Pipeline_VITIS_LOOP_1099_2_fu_37_ap_done;
wire    grp_unpack_60_Pipeline_VITIS_LOOP_1099_2_fu_37_ap_idle;
wire    grp_unpack_60_Pipeline_VITIS_LOOP_1099_2_fu_37_ap_ready;
wire    grp_unpack_60_Pipeline_VITIS_LOOP_1099_2_fu_37_s_pk_read;
wire   [15:0] grp_unpack_60_Pipeline_VITIS_LOOP_1099_2_fu_37_s_pkpv_din;
wire    grp_unpack_60_Pipeline_VITIS_LOOP_1099_2_fu_37_s_pkpv_write;
wire    grp_unpack_60_Pipeline_VITIS_LOOP_1108_3_fu_45_ap_start;
wire    grp_unpack_60_Pipeline_VITIS_LOOP_1108_3_fu_45_ap_done;
wire    grp_unpack_60_Pipeline_VITIS_LOOP_1108_3_fu_45_ap_idle;
wire    grp_unpack_60_Pipeline_VITIS_LOOP_1108_3_fu_45_ap_ready;
wire    grp_unpack_60_Pipeline_VITIS_LOOP_1108_3_fu_45_s_pk_read;
wire   [255:0] grp_unpack_60_Pipeline_VITIS_LOOP_1108_3_fu_45_t256_out;
wire    grp_unpack_60_Pipeline_VITIS_LOOP_1108_3_fu_45_t256_out_ap_vld;
reg    grp_unpack_60_Pipeline_VITIS_LOOP_1099_2_fu_37_ap_start_reg;
reg    ap_block_state1_ignore_call13;
wire    ap_CS_fsm_state2;
reg    grp_unpack_60_Pipeline_VITIS_LOOP_1108_3_fu_45_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg   [5:0] ap_NS_fsm;
reg    ap_block_state1;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 6'd1;
#0 grp_unpack_60_Pipeline_VITIS_LOOP_1099_2_fu_37_ap_start_reg = 1'b0;
#0 grp_unpack_60_Pipeline_VITIS_LOOP_1108_3_fu_45_ap_start_reg = 1'b0;
end

mlkem_accelerator_unpack_60_Pipeline_VITIS_LOOP_1099_2 grp_unpack_60_Pipeline_VITIS_LOOP_1099_2_fu_37(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_unpack_60_Pipeline_VITIS_LOOP_1099_2_fu_37_ap_start),
    .ap_done(grp_unpack_60_Pipeline_VITIS_LOOP_1099_2_fu_37_ap_done),
    .ap_idle(grp_unpack_60_Pipeline_VITIS_LOOP_1099_2_fu_37_ap_idle),
    .ap_ready(grp_unpack_60_Pipeline_VITIS_LOOP_1099_2_fu_37_ap_ready),
    .s_pk_dout(s_pk_dout),
    .s_pk_num_data_valid(9'd0),
    .s_pk_fifo_cap(9'd0),
    .s_pk_empty_n(s_pk_empty_n),
    .s_pk_read(grp_unpack_60_Pipeline_VITIS_LOOP_1099_2_fu_37_s_pk_read),
    .s_pkpv_din(grp_unpack_60_Pipeline_VITIS_LOOP_1099_2_fu_37_s_pkpv_din),
    .s_pkpv_num_data_valid(13'd0),
    .s_pkpv_fifo_cap(13'd0),
    .s_pkpv_full_n(s_pkpv_full_n),
    .s_pkpv_write(grp_unpack_60_Pipeline_VITIS_LOOP_1099_2_fu_37_s_pkpv_write)
);

mlkem_accelerator_unpack_60_Pipeline_VITIS_LOOP_1108_3 grp_unpack_60_Pipeline_VITIS_LOOP_1108_3_fu_45(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_unpack_60_Pipeline_VITIS_LOOP_1108_3_fu_45_ap_start),
    .ap_done(grp_unpack_60_Pipeline_VITIS_LOOP_1108_3_fu_45_ap_done),
    .ap_idle(grp_unpack_60_Pipeline_VITIS_LOOP_1108_3_fu_45_ap_idle),
    .ap_ready(grp_unpack_60_Pipeline_VITIS_LOOP_1108_3_fu_45_ap_ready),
    .s_pk_dout(s_pk_dout),
    .s_pk_num_data_valid(9'd0),
    .s_pk_fifo_cap(9'd0),
    .s_pk_empty_n(s_pk_empty_n),
    .s_pk_read(grp_unpack_60_Pipeline_VITIS_LOOP_1108_3_fu_45_s_pk_read),
    .t256_out(grp_unpack_60_Pipeline_VITIS_LOOP_1108_3_fu_45_t256_out),
    .t256_out_ap_vld(grp_unpack_60_Pipeline_VITIS_LOOP_1108_3_fu_45_t256_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((s_seed_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_unpack_60_Pipeline_VITIS_LOOP_1099_2_fu_37_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1_ignore_call13))) begin
            grp_unpack_60_Pipeline_VITIS_LOOP_1099_2_fu_37_ap_start_reg <= 1'b1;
        end else if ((grp_unpack_60_Pipeline_VITIS_LOOP_1099_2_fu_37_ap_ready == 1'b1)) begin
            grp_unpack_60_Pipeline_VITIS_LOOP_1099_2_fu_37_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_unpack_60_Pipeline_VITIS_LOOP_1108_3_fu_45_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_unpack_60_Pipeline_VITIS_LOOP_1108_3_fu_45_ap_start_reg <= 1'b1;
        end else if ((grp_unpack_60_Pipeline_VITIS_LOOP_1108_3_fu_45_ap_ready == 1'b1)) begin
            grp_unpack_60_Pipeline_VITIS_LOOP_1108_3_fu_45_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_unpack_60_Pipeline_VITIS_LOOP_1099_2_fu_37_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_unpack_60_Pipeline_VITIS_LOOP_1108_3_fu_45_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((s_seed_full_n == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if (((s_seed_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((s_seed_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        s_pk_read = grp_unpack_60_Pipeline_VITIS_LOOP_1108_3_fu_45_s_pk_read;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        s_pk_read = grp_unpack_60_Pipeline_VITIS_LOOP_1099_2_fu_37_s_pk_read;
    end else begin
        s_pk_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        s_pkpv_write = grp_unpack_60_Pipeline_VITIS_LOOP_1099_2_fu_37_s_pkpv_write;
    end else begin
        s_pkpv_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        s_seed_blk_n = s_seed_full_n;
    end else begin
        s_seed_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((s_seed_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        s_seed_write = 1'b1;
    end else begin
        s_seed_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_unpack_60_Pipeline_VITIS_LOOP_1099_2_fu_37_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_unpack_60_Pipeline_VITIS_LOOP_1108_3_fu_45_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((s_seed_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call13 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign grp_unpack_60_Pipeline_VITIS_LOOP_1099_2_fu_37_ap_start = grp_unpack_60_Pipeline_VITIS_LOOP_1099_2_fu_37_ap_start_reg;

assign grp_unpack_60_Pipeline_VITIS_LOOP_1108_3_fu_45_ap_start = grp_unpack_60_Pipeline_VITIS_LOOP_1108_3_fu_45_ap_start_reg;

assign s_pkpv_din = grp_unpack_60_Pipeline_VITIS_LOOP_1099_2_fu_37_s_pkpv_din;

assign s_seed_din = grp_unpack_60_Pipeline_VITIS_LOOP_1108_3_fu_45_t256_out;

assign start_out = real_start;

endmodule //mlkem_accelerator_unpack_60
