// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mlkem_accelerator_split_unsigned_char_43 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        s_kr_orig_dout,
        s_kr_orig_num_data_valid,
        s_kr_orig_fifo_cap,
        s_kr_orig_empty_n,
        s_kr_orig_read,
        s_coins_orig_din,
        s_coins_orig_num_data_valid,
        s_coins_orig_fifo_cap,
        s_coins_orig_full_n,
        s_coins_orig_write,
        s_krl_din,
        s_krl_num_data_valid,
        s_krl_fifo_cap,
        s_krl_full_n,
        s_krl_write,
        start_out,
        start_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] s_kr_orig_dout;
input  [7:0] s_kr_orig_num_data_valid;
input  [7:0] s_kr_orig_fifo_cap;
input   s_kr_orig_empty_n;
output   s_kr_orig_read;
output  [7:0] s_coins_orig_din;
input  [5:0] s_coins_orig_num_data_valid;
input  [5:0] s_coins_orig_fifo_cap;
input   s_coins_orig_full_n;
output   s_coins_orig_write;
output  [7:0] s_krl_din;
input  [7:0] s_krl_num_data_valid;
input  [7:0] s_krl_fifo_cap;
input   s_krl_full_n;
output   s_krl_write;
output   start_out;
output   start_write;

reg ap_idle;
reg s_kr_orig_read;
reg s_coins_orig_write;
reg s_krl_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] icmp_ln989_reg_173;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln987_fu_100_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    s_kr_orig_blk_n;
wire    ap_block_pp0_stage0;
reg    s_krl_blk_n;
reg    s_coins_orig_blk_n;
wire   [0:0] icmp_ln989_fu_122_p2;
reg    ap_block_pp0_stage0_11001;
wire   [31:0] grp_fu_78_p2;
reg   [31:0] counter_6_reg_177;
wire   [0:0] icmp_ln996_fu_128_p2;
reg   [0:0] icmp_ln996_reg_182;
reg   [31:0] counter_fu_48;
wire   [31:0] counter_7_fu_144_p3;
reg   [31:0] ap_sig_allocacmp_counter_4;
wire    ap_loop_init;
reg   [6:0] i_fu_52;
wire   [6:0] i_26_fu_106_p2;
reg   [6:0] ap_sig_allocacmp_i_25;
reg    ap_block_pp0_stage0_01001;
wire   [26:0] tmp_fu_112_p4;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_221;
reg    ap_condition_116;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 counter_fu_48 = 32'd0;
#0 i_fu_52 = 7'd0;
end

mlkem_accelerator_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((1'b1 == ap_condition_221)) begin
            counter_fu_48 <= grp_fu_78_p2;
        end else if (((ap_start_int == 1'b1) & (ap_loop_init == 1'b1))) begin
            counter_fu_48 <= 32'd0;
        end else if (((icmp_ln989_reg_173 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            counter_fu_48 <= counter_7_fu_144_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_116)) begin
        if ((icmp_ln987_fu_100_p2 == 1'd0)) begin
            i_fu_52 <= i_26_fu_106_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_52 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        counter_6_reg_177 <= grp_fu_78_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln989_reg_173 <= icmp_ln989_fu_122_p2;
        icmp_ln996_reg_182 <= icmp_ln996_fu_128_p2;
    end
end

always @ (*) begin
    if (((icmp_ln987_fu_100_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_start_int == 1'b1) & (ap_loop_init == 1'b1))) begin
            ap_sig_allocacmp_counter_4 = 32'd0;
        end else if (((icmp_ln989_reg_173 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            ap_sig_allocacmp_counter_4 = counter_7_fu_144_p3;
        end else begin
            ap_sig_allocacmp_counter_4 = counter_fu_48;
        end
    end else begin
        ap_sig_allocacmp_counter_4 = counter_fu_48;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_25 = 7'd0;
    end else begin
        ap_sig_allocacmp_i_25 = i_fu_52;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln989_reg_173 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_coins_orig_blk_n = s_coins_orig_full_n;
    end else begin
        s_coins_orig_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln989_reg_173 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_coins_orig_write = 1'b1;
    end else begin
        s_coins_orig_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_kr_orig_blk_n = s_kr_orig_empty_n;
    end else begin
        s_kr_orig_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_kr_orig_read = 1'b1;
    end else begin
        s_kr_orig_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln989_reg_173 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_krl_blk_n = s_krl_full_n;
    end else begin
        s_krl_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln989_reg_173 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_krl_write = 1'b1;
    end else begin
        s_krl_write = 1'b0;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((s_kr_orig_empty_n == 1'b0) | ((s_krl_full_n == 1'b0) & (icmp_ln989_reg_173 == 1'd1)) | ((icmp_ln989_reg_173 == 1'd0) & (s_coins_orig_full_n == 1'b0)));
end

always @ (*) begin
    ap_condition_116 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_221 = ((icmp_ln987_fu_100_p2 == 1'd0) & (ap_start_int == 1'b1) & (icmp_ln989_fu_122_p2 == 1'd1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = internal_ap_ready;

assign counter_7_fu_144_p3 = ((icmp_ln996_reg_182[0:0] == 1'b1) ? 32'd0 : counter_6_reg_177);

assign grp_fu_78_p2 = (ap_sig_allocacmp_counter_4 + 32'd1);

assign i_26_fu_106_p2 = (ap_sig_allocacmp_i_25 + 7'd1);

assign icmp_ln987_fu_100_p2 = ((ap_sig_allocacmp_i_25 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln989_fu_122_p2 = (($signed(tmp_fu_112_p4) < $signed(27'd1)) ? 1'b1 : 1'b0);

assign icmp_ln996_fu_128_p2 = ((grp_fu_78_p2 == 32'd64) ? 1'b1 : 1'b0);

assign s_coins_orig_din = s_kr_orig_dout;

assign s_krl_din = s_kr_orig_dout;

assign start_out = real_start;

assign tmp_fu_112_p4 = {{ap_sig_allocacmp_counter_4[31:5]}};

endmodule //mlkem_accelerator_split_unsigned_char_43
