// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mlkem_accelerator_writemem_77 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        m_axi_gmemct_AWVALID,
        m_axi_gmemct_AWREADY,
        m_axi_gmemct_AWADDR,
        m_axi_gmemct_AWID,
        m_axi_gmemct_AWLEN,
        m_axi_gmemct_AWSIZE,
        m_axi_gmemct_AWBURST,
        m_axi_gmemct_AWLOCK,
        m_axi_gmemct_AWCACHE,
        m_axi_gmemct_AWPROT,
        m_axi_gmemct_AWQOS,
        m_axi_gmemct_AWREGION,
        m_axi_gmemct_AWUSER,
        m_axi_gmemct_WVALID,
        m_axi_gmemct_WREADY,
        m_axi_gmemct_WDATA,
        m_axi_gmemct_WSTRB,
        m_axi_gmemct_WLAST,
        m_axi_gmemct_WID,
        m_axi_gmemct_WUSER,
        m_axi_gmemct_ARVALID,
        m_axi_gmemct_ARREADY,
        m_axi_gmemct_ARADDR,
        m_axi_gmemct_ARID,
        m_axi_gmemct_ARLEN,
        m_axi_gmemct_ARSIZE,
        m_axi_gmemct_ARBURST,
        m_axi_gmemct_ARLOCK,
        m_axi_gmemct_ARCACHE,
        m_axi_gmemct_ARPROT,
        m_axi_gmemct_ARQOS,
        m_axi_gmemct_ARREGION,
        m_axi_gmemct_ARUSER,
        m_axi_gmemct_RVALID,
        m_axi_gmemct_RREADY,
        m_axi_gmemct_RDATA,
        m_axi_gmemct_RLAST,
        m_axi_gmemct_RID,
        m_axi_gmemct_RFIFONUM,
        m_axi_gmemct_RUSER,
        m_axi_gmemct_RRESP,
        m_axi_gmemct_BVALID,
        m_axi_gmemct_BREADY,
        m_axi_gmemct_BRESP,
        m_axi_gmemct_BID,
        m_axi_gmemct_BUSER,
        out_r_dout,
        out_r_num_data_valid,
        out_r_fifo_cap,
        out_r_empty_n,
        out_r_read,
        s_ct_orig_dout,
        s_ct_orig_num_data_valid,
        s_ct_orig_fifo_cap,
        s_ct_orig_empty_n,
        s_ct_orig_read
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   m_axi_gmemct_AWVALID;
input   m_axi_gmemct_AWREADY;
output  [31:0] m_axi_gmemct_AWADDR;
output  [0:0] m_axi_gmemct_AWID;
output  [31:0] m_axi_gmemct_AWLEN;
output  [2:0] m_axi_gmemct_AWSIZE;
output  [1:0] m_axi_gmemct_AWBURST;
output  [1:0] m_axi_gmemct_AWLOCK;
output  [3:0] m_axi_gmemct_AWCACHE;
output  [2:0] m_axi_gmemct_AWPROT;
output  [3:0] m_axi_gmemct_AWQOS;
output  [3:0] m_axi_gmemct_AWREGION;
output  [0:0] m_axi_gmemct_AWUSER;
output   m_axi_gmemct_WVALID;
input   m_axi_gmemct_WREADY;
output  [7:0] m_axi_gmemct_WDATA;
output  [0:0] m_axi_gmemct_WSTRB;
output   m_axi_gmemct_WLAST;
output  [0:0] m_axi_gmemct_WID;
output  [0:0] m_axi_gmemct_WUSER;
output   m_axi_gmemct_ARVALID;
input   m_axi_gmemct_ARREADY;
output  [31:0] m_axi_gmemct_ARADDR;
output  [0:0] m_axi_gmemct_ARID;
output  [31:0] m_axi_gmemct_ARLEN;
output  [2:0] m_axi_gmemct_ARSIZE;
output  [1:0] m_axi_gmemct_ARBURST;
output  [1:0] m_axi_gmemct_ARLOCK;
output  [3:0] m_axi_gmemct_ARCACHE;
output  [2:0] m_axi_gmemct_ARPROT;
output  [3:0] m_axi_gmemct_ARQOS;
output  [3:0] m_axi_gmemct_ARREGION;
output  [0:0] m_axi_gmemct_ARUSER;
input   m_axi_gmemct_RVALID;
output   m_axi_gmemct_RREADY;
input  [7:0] m_axi_gmemct_RDATA;
input   m_axi_gmemct_RLAST;
input  [0:0] m_axi_gmemct_RID;
input  [10:0] m_axi_gmemct_RFIFONUM;
input  [0:0] m_axi_gmemct_RUSER;
input  [1:0] m_axi_gmemct_RRESP;
input   m_axi_gmemct_BVALID;
output   m_axi_gmemct_BREADY;
input  [1:0] m_axi_gmemct_BRESP;
input  [0:0] m_axi_gmemct_BID;
input  [0:0] m_axi_gmemct_BUSER;
input  [31:0] out_r_dout;
input  [7:0] out_r_num_data_valid;
input  [7:0] out_r_fifo_cap;
input   out_r_empty_n;
output   out_r_read;
input  [7:0] s_ct_orig_dout;
input  [8:0] s_ct_orig_num_data_valid;
input  [8:0] s_ct_orig_fifo_cap;
input   s_ct_orig_empty_n;
output   s_ct_orig_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_gmemct_AWVALID;
reg[31:0] m_axi_gmemct_AWADDR;
reg[0:0] m_axi_gmemct_AWID;
reg[31:0] m_axi_gmemct_AWLEN;
reg[2:0] m_axi_gmemct_AWSIZE;
reg[1:0] m_axi_gmemct_AWBURST;
reg[1:0] m_axi_gmemct_AWLOCK;
reg[3:0] m_axi_gmemct_AWCACHE;
reg[2:0] m_axi_gmemct_AWPROT;
reg[3:0] m_axi_gmemct_AWQOS;
reg[3:0] m_axi_gmemct_AWREGION;
reg[0:0] m_axi_gmemct_AWUSER;
reg m_axi_gmemct_WVALID;
reg m_axi_gmemct_BREADY;
reg out_r_read;
reg s_ct_orig_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    gmemct_blk_n_AW;
wire    ap_CS_fsm_state2;
reg    gmemct_blk_n_B;
wire    ap_CS_fsm_state9;
reg    out_r_blk_n;
reg   [31:0] out_read_reg_73;
reg    ap_block_state1;
wire    grp_writemem_77_Pipeline_writemem_fu_58_ap_start;
wire    grp_writemem_77_Pipeline_writemem_fu_58_ap_done;
wire    grp_writemem_77_Pipeline_writemem_fu_58_ap_idle;
wire    grp_writemem_77_Pipeline_writemem_fu_58_ap_ready;
wire    grp_writemem_77_Pipeline_writemem_fu_58_s_ct_orig_read;
wire    grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_AWVALID;
wire   [31:0] grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_AWADDR;
wire   [0:0] grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_AWID;
wire   [31:0] grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_AWLEN;
wire   [2:0] grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_AWSIZE;
wire   [1:0] grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_AWBURST;
wire   [1:0] grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_AWLOCK;
wire   [3:0] grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_AWCACHE;
wire   [2:0] grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_AWPROT;
wire   [3:0] grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_AWQOS;
wire   [3:0] grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_AWREGION;
wire   [0:0] grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_AWUSER;
wire    grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_WVALID;
wire   [7:0] grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_WDATA;
wire   [0:0] grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_WSTRB;
wire    grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_WLAST;
wire   [0:0] grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_WID;
wire   [0:0] grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_WUSER;
wire    grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_ARVALID;
wire   [31:0] grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_ARADDR;
wire   [0:0] grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_ARID;
wire   [31:0] grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_ARLEN;
wire   [2:0] grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_ARSIZE;
wire   [1:0] grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_ARBURST;
wire   [1:0] grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_ARLOCK;
wire   [3:0] grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_ARCACHE;
wire   [2:0] grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_ARPROT;
wire   [3:0] grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_ARQOS;
wire   [3:0] grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_ARREGION;
wire   [0:0] grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_ARUSER;
wire    grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_RREADY;
wire    grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_BREADY;
reg    grp_writemem_77_Pipeline_writemem_fu_58_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [8:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 9'd1;
#0 grp_writemem_77_Pipeline_writemem_fu_58_ap_start_reg = 1'b0;
end

mlkem_accelerator_writemem_77_Pipeline_writemem grp_writemem_77_Pipeline_writemem_fu_58(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_writemem_77_Pipeline_writemem_fu_58_ap_start),
    .ap_done(grp_writemem_77_Pipeline_writemem_fu_58_ap_done),
    .ap_idle(grp_writemem_77_Pipeline_writemem_fu_58_ap_idle),
    .ap_ready(grp_writemem_77_Pipeline_writemem_fu_58_ap_ready),
    .s_ct_orig_dout(s_ct_orig_dout),
    .s_ct_orig_num_data_valid(9'd0),
    .s_ct_orig_fifo_cap(9'd0),
    .s_ct_orig_empty_n(s_ct_orig_empty_n),
    .s_ct_orig_read(grp_writemem_77_Pipeline_writemem_fu_58_s_ct_orig_read),
    .m_axi_gmemct_AWVALID(grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_AWVALID),
    .m_axi_gmemct_AWREADY(m_axi_gmemct_AWREADY),
    .m_axi_gmemct_AWADDR(grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_AWADDR),
    .m_axi_gmemct_AWID(grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_AWID),
    .m_axi_gmemct_AWLEN(grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_AWLEN),
    .m_axi_gmemct_AWSIZE(grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_AWSIZE),
    .m_axi_gmemct_AWBURST(grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_AWBURST),
    .m_axi_gmemct_AWLOCK(grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_AWLOCK),
    .m_axi_gmemct_AWCACHE(grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_AWCACHE),
    .m_axi_gmemct_AWPROT(grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_AWPROT),
    .m_axi_gmemct_AWQOS(grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_AWQOS),
    .m_axi_gmemct_AWREGION(grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_AWREGION),
    .m_axi_gmemct_AWUSER(grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_AWUSER),
    .m_axi_gmemct_WVALID(grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_WVALID),
    .m_axi_gmemct_WREADY(m_axi_gmemct_WREADY),
    .m_axi_gmemct_WDATA(grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_WDATA),
    .m_axi_gmemct_WSTRB(grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_WSTRB),
    .m_axi_gmemct_WLAST(grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_WLAST),
    .m_axi_gmemct_WID(grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_WID),
    .m_axi_gmemct_WUSER(grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_WUSER),
    .m_axi_gmemct_ARVALID(grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_ARVALID),
    .m_axi_gmemct_ARREADY(1'b0),
    .m_axi_gmemct_ARADDR(grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_ARADDR),
    .m_axi_gmemct_ARID(grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_ARID),
    .m_axi_gmemct_ARLEN(grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_ARLEN),
    .m_axi_gmemct_ARSIZE(grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_ARSIZE),
    .m_axi_gmemct_ARBURST(grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_ARBURST),
    .m_axi_gmemct_ARLOCK(grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_ARLOCK),
    .m_axi_gmemct_ARCACHE(grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_ARCACHE),
    .m_axi_gmemct_ARPROT(grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_ARPROT),
    .m_axi_gmemct_ARQOS(grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_ARQOS),
    .m_axi_gmemct_ARREGION(grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_ARREGION),
    .m_axi_gmemct_ARUSER(grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_ARUSER),
    .m_axi_gmemct_RVALID(1'b0),
    .m_axi_gmemct_RREADY(grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_RREADY),
    .m_axi_gmemct_RDATA(8'd0),
    .m_axi_gmemct_RLAST(1'b0),
    .m_axi_gmemct_RID(1'd0),
    .m_axi_gmemct_RFIFONUM(11'd0),
    .m_axi_gmemct_RUSER(1'd0),
    .m_axi_gmemct_RRESP(2'd0),
    .m_axi_gmemct_BVALID(m_axi_gmemct_BVALID),
    .m_axi_gmemct_BREADY(grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_BREADY),
    .m_axi_gmemct_BRESP(m_axi_gmemct_BRESP),
    .m_axi_gmemct_BID(m_axi_gmemct_BID),
    .m_axi_gmemct_BUSER(m_axi_gmemct_BUSER),
    .out_load(out_read_reg_73)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((m_axi_gmemct_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_writemem_77_Pipeline_writemem_fu_58_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_writemem_77_Pipeline_writemem_fu_58_ap_start_reg <= 1'b1;
        end else if ((grp_writemem_77_Pipeline_writemem_fu_58_ap_ready == 1'b1)) begin
            grp_writemem_77_Pipeline_writemem_fu_58_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        out_read_reg_73 <= out_r_dout;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_gmemct_AWREADY == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_writemem_77_Pipeline_writemem_fu_58_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((m_axi_gmemct_BVALID == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_gmemct_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_gmemct_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        gmemct_blk_n_AW = m_axi_gmemct_AWREADY;
    end else begin
        gmemct_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        gmemct_blk_n_B = m_axi_gmemct_BVALID;
    end else begin
        gmemct_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((m_axi_gmemct_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmemct_AWADDR = out_read_reg_73;
    end else if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmemct_AWADDR = grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_AWADDR;
    end else begin
        m_axi_gmemct_AWADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmemct_AWBURST = grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_AWBURST;
    end else begin
        m_axi_gmemct_AWBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmemct_AWCACHE = grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_AWCACHE;
    end else begin
        m_axi_gmemct_AWCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmemct_AWID = grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_AWID;
    end else begin
        m_axi_gmemct_AWID = 1'd0;
    end
end

always @ (*) begin
    if (((m_axi_gmemct_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmemct_AWLEN = 32'd768;
    end else if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmemct_AWLEN = grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_AWLEN;
    end else begin
        m_axi_gmemct_AWLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmemct_AWLOCK = grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_AWLOCK;
    end else begin
        m_axi_gmemct_AWLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmemct_AWPROT = grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_AWPROT;
    end else begin
        m_axi_gmemct_AWPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmemct_AWQOS = grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_AWQOS;
    end else begin
        m_axi_gmemct_AWQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmemct_AWREGION = grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_AWREGION;
    end else begin
        m_axi_gmemct_AWREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmemct_AWSIZE = grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_AWSIZE;
    end else begin
        m_axi_gmemct_AWSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmemct_AWUSER = grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_AWUSER;
    end else begin
        m_axi_gmemct_AWUSER = 1'd0;
    end
end

always @ (*) begin
    if (((m_axi_gmemct_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmemct_AWVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmemct_AWVALID = grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_AWVALID;
    end else begin
        m_axi_gmemct_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_gmemct_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmemct_BREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmemct_BREADY = grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_BREADY;
    end else begin
        m_axi_gmemct_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmemct_WVALID = grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_WVALID;
    end else begin
        m_axi_gmemct_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        out_r_blk_n = out_r_empty_n;
    end else begin
        out_r_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        out_r_read = 1'b1;
    end else begin
        out_r_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        s_ct_orig_read = grp_writemem_77_Pipeline_writemem_fu_58_s_ct_orig_read;
    end else begin
        s_ct_orig_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((m_axi_gmemct_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_writemem_77_Pipeline_writemem_fu_58_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((m_axi_gmemct_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((out_r_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign grp_writemem_77_Pipeline_writemem_fu_58_ap_start = grp_writemem_77_Pipeline_writemem_fu_58_ap_start_reg;

assign m_axi_gmemct_ARADDR = 32'd0;

assign m_axi_gmemct_ARBURST = 2'd0;

assign m_axi_gmemct_ARCACHE = 4'd0;

assign m_axi_gmemct_ARID = 1'd0;

assign m_axi_gmemct_ARLEN = 32'd0;

assign m_axi_gmemct_ARLOCK = 2'd0;

assign m_axi_gmemct_ARPROT = 3'd0;

assign m_axi_gmemct_ARQOS = 4'd0;

assign m_axi_gmemct_ARREGION = 4'd0;

assign m_axi_gmemct_ARSIZE = 3'd0;

assign m_axi_gmemct_ARUSER = 1'd0;

assign m_axi_gmemct_ARVALID = 1'b0;

assign m_axi_gmemct_RREADY = 1'b0;

assign m_axi_gmemct_WDATA = grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_WDATA;

assign m_axi_gmemct_WID = grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_WID;

assign m_axi_gmemct_WLAST = grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_WLAST;

assign m_axi_gmemct_WSTRB = grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_WSTRB;

assign m_axi_gmemct_WUSER = grp_writemem_77_Pipeline_writemem_fu_58_m_axi_gmemct_WUSER;

endmodule //mlkem_accelerator_writemem_77
