// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mlkem_accelerator_readmem_unsigned_char_1 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        m_axi_gmemsk_AWVALID,
        m_axi_gmemsk_AWREADY,
        m_axi_gmemsk_AWADDR,
        m_axi_gmemsk_AWID,
        m_axi_gmemsk_AWLEN,
        m_axi_gmemsk_AWSIZE,
        m_axi_gmemsk_AWBURST,
        m_axi_gmemsk_AWLOCK,
        m_axi_gmemsk_AWCACHE,
        m_axi_gmemsk_AWPROT,
        m_axi_gmemsk_AWQOS,
        m_axi_gmemsk_AWREGION,
        m_axi_gmemsk_AWUSER,
        m_axi_gmemsk_WVALID,
        m_axi_gmemsk_WREADY,
        m_axi_gmemsk_WDATA,
        m_axi_gmemsk_WSTRB,
        m_axi_gmemsk_WLAST,
        m_axi_gmemsk_WID,
        m_axi_gmemsk_WUSER,
        m_axi_gmemsk_ARVALID,
        m_axi_gmemsk_ARREADY,
        m_axi_gmemsk_ARADDR,
        m_axi_gmemsk_ARID,
        m_axi_gmemsk_ARLEN,
        m_axi_gmemsk_ARSIZE,
        m_axi_gmemsk_ARBURST,
        m_axi_gmemsk_ARLOCK,
        m_axi_gmemsk_ARCACHE,
        m_axi_gmemsk_ARPROT,
        m_axi_gmemsk_ARQOS,
        m_axi_gmemsk_ARREGION,
        m_axi_gmemsk_ARUSER,
        m_axi_gmemsk_RVALID,
        m_axi_gmemsk_RREADY,
        m_axi_gmemsk_RDATA,
        m_axi_gmemsk_RLAST,
        m_axi_gmemsk_RID,
        m_axi_gmemsk_RFIFONUM,
        m_axi_gmemsk_RUSER,
        m_axi_gmemsk_RRESP,
        m_axi_gmemsk_BVALID,
        m_axi_gmemsk_BREADY,
        m_axi_gmemsk_BRESP,
        m_axi_gmemsk_BID,
        m_axi_gmemsk_BUSER,
        in_r,
        s_sk_orig_din,
        s_sk_orig_num_data_valid,
        s_sk_orig_fifo_cap,
        s_sk_orig_full_n,
        s_sk_orig_write
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
output   m_axi_gmemsk_AWVALID;
input   m_axi_gmemsk_AWREADY;
output  [31:0] m_axi_gmemsk_AWADDR;
output  [0:0] m_axi_gmemsk_AWID;
output  [31:0] m_axi_gmemsk_AWLEN;
output  [2:0] m_axi_gmemsk_AWSIZE;
output  [1:0] m_axi_gmemsk_AWBURST;
output  [1:0] m_axi_gmemsk_AWLOCK;
output  [3:0] m_axi_gmemsk_AWCACHE;
output  [2:0] m_axi_gmemsk_AWPROT;
output  [3:0] m_axi_gmemsk_AWQOS;
output  [3:0] m_axi_gmemsk_AWREGION;
output  [0:0] m_axi_gmemsk_AWUSER;
output   m_axi_gmemsk_WVALID;
input   m_axi_gmemsk_WREADY;
output  [7:0] m_axi_gmemsk_WDATA;
output  [0:0] m_axi_gmemsk_WSTRB;
output   m_axi_gmemsk_WLAST;
output  [0:0] m_axi_gmemsk_WID;
output  [0:0] m_axi_gmemsk_WUSER;
output   m_axi_gmemsk_ARVALID;
input   m_axi_gmemsk_ARREADY;
output  [31:0] m_axi_gmemsk_ARADDR;
output  [0:0] m_axi_gmemsk_ARID;
output  [31:0] m_axi_gmemsk_ARLEN;
output  [2:0] m_axi_gmemsk_ARSIZE;
output  [1:0] m_axi_gmemsk_ARBURST;
output  [1:0] m_axi_gmemsk_ARLOCK;
output  [3:0] m_axi_gmemsk_ARCACHE;
output  [2:0] m_axi_gmemsk_ARPROT;
output  [3:0] m_axi_gmemsk_ARQOS;
output  [3:0] m_axi_gmemsk_ARREGION;
output  [0:0] m_axi_gmemsk_ARUSER;
input   m_axi_gmemsk_RVALID;
output   m_axi_gmemsk_RREADY;
input  [7:0] m_axi_gmemsk_RDATA;
input   m_axi_gmemsk_RLAST;
input  [0:0] m_axi_gmemsk_RID;
input  [10:0] m_axi_gmemsk_RFIFONUM;
input  [0:0] m_axi_gmemsk_RUSER;
input  [1:0] m_axi_gmemsk_RRESP;
input   m_axi_gmemsk_BVALID;
output   m_axi_gmemsk_BREADY;
input  [1:0] m_axi_gmemsk_BRESP;
input  [0:0] m_axi_gmemsk_BID;
input  [0:0] m_axi_gmemsk_BUSER;
input  [31:0] in_r;
output  [7:0] s_sk_orig_din;
input  [12:0] s_sk_orig_num_data_valid;
input  [12:0] s_sk_orig_fifo_cap;
input   s_sk_orig_full_n;
output   s_sk_orig_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg m_axi_gmemsk_ARVALID;
reg[31:0] m_axi_gmemsk_ARADDR;
reg[0:0] m_axi_gmemsk_ARID;
reg[31:0] m_axi_gmemsk_ARLEN;
reg[2:0] m_axi_gmemsk_ARSIZE;
reg[1:0] m_axi_gmemsk_ARBURST;
reg[1:0] m_axi_gmemsk_ARLOCK;
reg[3:0] m_axi_gmemsk_ARCACHE;
reg[2:0] m_axi_gmemsk_ARPROT;
reg[3:0] m_axi_gmemsk_ARQOS;
reg[3:0] m_axi_gmemsk_ARREGION;
reg[0:0] m_axi_gmemsk_ARUSER;
reg m_axi_gmemsk_RREADY;
reg s_sk_orig_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    gmemsk_blk_n_AR;
reg    ap_block_state1;
wire    grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_ap_start;
wire    grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_ap_done;
wire    grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_ap_idle;
wire    grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_ap_ready;
wire    grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_AWVALID;
wire   [31:0] grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_AWADDR;
wire   [0:0] grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_AWID;
wire   [31:0] grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_AWLEN;
wire   [2:0] grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_AWSIZE;
wire   [1:0] grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_AWBURST;
wire   [1:0] grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_AWLOCK;
wire   [3:0] grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_AWCACHE;
wire   [2:0] grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_AWPROT;
wire   [3:0] grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_AWQOS;
wire   [3:0] grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_AWREGION;
wire   [0:0] grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_AWUSER;
wire    grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_WVALID;
wire   [7:0] grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_WDATA;
wire   [0:0] grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_WSTRB;
wire    grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_WLAST;
wire   [0:0] grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_WID;
wire   [0:0] grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_WUSER;
wire    grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_ARVALID;
wire   [31:0] grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_ARADDR;
wire   [0:0] grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_ARID;
wire   [31:0] grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_ARLEN;
wire   [2:0] grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_ARSIZE;
wire   [1:0] grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_ARBURST;
wire   [1:0] grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_ARLOCK;
wire   [3:0] grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_ARCACHE;
wire   [2:0] grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_ARPROT;
wire   [3:0] grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_ARQOS;
wire   [3:0] grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_ARREGION;
wire   [0:0] grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_ARUSER;
wire    grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_RREADY;
wire    grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_BREADY;
wire   [7:0] grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_s_sk_orig_din;
wire    grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_s_sk_orig_write;
reg    grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
reg   [9:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 10'd1;
#0 grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_ap_start_reg = 1'b0;
end

mlkem_accelerator_readmem_unsigned_char_1_Pipeline_readmem grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_ap_start),
    .ap_done(grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_ap_done),
    .ap_idle(grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_ap_idle),
    .ap_ready(grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_ap_ready),
    .m_axi_gmemsk_AWVALID(grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_AWVALID),
    .m_axi_gmemsk_AWREADY(1'b0),
    .m_axi_gmemsk_AWADDR(grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_AWADDR),
    .m_axi_gmemsk_AWID(grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_AWID),
    .m_axi_gmemsk_AWLEN(grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_AWLEN),
    .m_axi_gmemsk_AWSIZE(grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_AWSIZE),
    .m_axi_gmemsk_AWBURST(grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_AWBURST),
    .m_axi_gmemsk_AWLOCK(grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_AWLOCK),
    .m_axi_gmemsk_AWCACHE(grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_AWCACHE),
    .m_axi_gmemsk_AWPROT(grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_AWPROT),
    .m_axi_gmemsk_AWQOS(grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_AWQOS),
    .m_axi_gmemsk_AWREGION(grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_AWREGION),
    .m_axi_gmemsk_AWUSER(grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_AWUSER),
    .m_axi_gmemsk_WVALID(grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_WVALID),
    .m_axi_gmemsk_WREADY(1'b0),
    .m_axi_gmemsk_WDATA(grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_WDATA),
    .m_axi_gmemsk_WSTRB(grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_WSTRB),
    .m_axi_gmemsk_WLAST(grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_WLAST),
    .m_axi_gmemsk_WID(grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_WID),
    .m_axi_gmemsk_WUSER(grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_WUSER),
    .m_axi_gmemsk_ARVALID(grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_ARVALID),
    .m_axi_gmemsk_ARREADY(m_axi_gmemsk_ARREADY),
    .m_axi_gmemsk_ARADDR(grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_ARADDR),
    .m_axi_gmemsk_ARID(grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_ARID),
    .m_axi_gmemsk_ARLEN(grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_ARLEN),
    .m_axi_gmemsk_ARSIZE(grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_ARSIZE),
    .m_axi_gmemsk_ARBURST(grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_ARBURST),
    .m_axi_gmemsk_ARLOCK(grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_ARLOCK),
    .m_axi_gmemsk_ARCACHE(grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_ARCACHE),
    .m_axi_gmemsk_ARPROT(grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_ARPROT),
    .m_axi_gmemsk_ARQOS(grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_ARQOS),
    .m_axi_gmemsk_ARREGION(grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_ARREGION),
    .m_axi_gmemsk_ARUSER(grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_ARUSER),
    .m_axi_gmemsk_RVALID(m_axi_gmemsk_RVALID),
    .m_axi_gmemsk_RREADY(grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_RREADY),
    .m_axi_gmemsk_RDATA(m_axi_gmemsk_RDATA),
    .m_axi_gmemsk_RLAST(m_axi_gmemsk_RLAST),
    .m_axi_gmemsk_RID(m_axi_gmemsk_RID),
    .m_axi_gmemsk_RFIFONUM(m_axi_gmemsk_RFIFONUM),
    .m_axi_gmemsk_RUSER(m_axi_gmemsk_RUSER),
    .m_axi_gmemsk_RRESP(m_axi_gmemsk_RRESP),
    .m_axi_gmemsk_BVALID(1'b0),
    .m_axi_gmemsk_BREADY(grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_BREADY),
    .m_axi_gmemsk_BRESP(2'd0),
    .m_axi_gmemsk_BID(1'd0),
    .m_axi_gmemsk_BUSER(1'd0),
    .s_sk_orig_din(grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_s_sk_orig_din),
    .s_sk_orig_num_data_valid(13'd0),
    .s_sk_orig_fifo_cap(13'd0),
    .s_sk_orig_full_n(s_sk_orig_full_n),
    .s_sk_orig_write(grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_s_sk_orig_write),
    .in_r(in_r)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state10) & (grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_ap_done == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_ap_start_reg <= 1'b1;
        end else if ((grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_ap_ready == 1'b1)) begin
            grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_gmemsk_ARREADY == 1'b0) | (1'b1 == ap_block_state1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        gmemsk_blk_n_AR = m_axi_gmemsk_ARREADY;
    end else begin
        gmemsk_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_ap_done == 1'b1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((m_axi_gmemsk_ARREADY == 1'b0) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1))) begin
        m_axi_gmemsk_ARADDR = in_r;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmemsk_ARADDR = grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_ARADDR;
    end else begin
        m_axi_gmemsk_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmemsk_ARBURST = grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_ARBURST;
    end else begin
        m_axi_gmemsk_ARBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmemsk_ARCACHE = grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_ARCACHE;
    end else begin
        m_axi_gmemsk_ARCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmemsk_ARID = grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_ARID;
    end else begin
        m_axi_gmemsk_ARID = 1'd0;
    end
end

always @ (*) begin
    if ((~((m_axi_gmemsk_ARREADY == 1'b0) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1))) begin
        m_axi_gmemsk_ARLEN = 32'd1632;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmemsk_ARLEN = grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_ARLEN;
    end else begin
        m_axi_gmemsk_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmemsk_ARLOCK = grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_ARLOCK;
    end else begin
        m_axi_gmemsk_ARLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmemsk_ARPROT = grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_ARPROT;
    end else begin
        m_axi_gmemsk_ARPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmemsk_ARQOS = grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_ARQOS;
    end else begin
        m_axi_gmemsk_ARQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmemsk_ARREGION = grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_ARREGION;
    end else begin
        m_axi_gmemsk_ARREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmemsk_ARSIZE = grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_ARSIZE;
    end else begin
        m_axi_gmemsk_ARSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmemsk_ARUSER = grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_ARUSER;
    end else begin
        m_axi_gmemsk_ARUSER = 1'd0;
    end
end

always @ (*) begin
    if ((~((m_axi_gmemsk_ARREADY == 1'b0) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1))) begin
        m_axi_gmemsk_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmemsk_ARVALID = grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_ARVALID;
    end else begin
        m_axi_gmemsk_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmemsk_RREADY = grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_m_axi_gmemsk_RREADY;
    end else begin
        m_axi_gmemsk_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        s_sk_orig_write = grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_s_sk_orig_write;
    end else begin
        s_sk_orig_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((m_axi_gmemsk_ARREADY == 1'b0) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_ap_start = grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_ap_start_reg;

assign m_axi_gmemsk_AWADDR = 32'd0;

assign m_axi_gmemsk_AWBURST = 2'd0;

assign m_axi_gmemsk_AWCACHE = 4'd0;

assign m_axi_gmemsk_AWID = 1'd0;

assign m_axi_gmemsk_AWLEN = 32'd0;

assign m_axi_gmemsk_AWLOCK = 2'd0;

assign m_axi_gmemsk_AWPROT = 3'd0;

assign m_axi_gmemsk_AWQOS = 4'd0;

assign m_axi_gmemsk_AWREGION = 4'd0;

assign m_axi_gmemsk_AWSIZE = 3'd0;

assign m_axi_gmemsk_AWUSER = 1'd0;

assign m_axi_gmemsk_AWVALID = 1'b0;

assign m_axi_gmemsk_BREADY = 1'b0;

assign m_axi_gmemsk_WDATA = 8'd0;

assign m_axi_gmemsk_WID = 1'd0;

assign m_axi_gmemsk_WLAST = 1'b0;

assign m_axi_gmemsk_WSTRB = 1'd0;

assign m_axi_gmemsk_WUSER = 1'd0;

assign m_axi_gmemsk_WVALID = 1'b0;

assign s_sk_orig_din = grp_readmem_unsigned_char_1_Pipeline_readmem_fu_47_s_sk_orig_din;

assign start_out = real_start;

endmodule //mlkem_accelerator_readmem_unsigned_char_1
