// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mlkem_accelerator_absorb (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        p_read16,
        p_read17,
        p_read18,
        p_read19,
        p_read20,
        p_read21,
        p_read22,
        p_read23,
        p_read24,
        k_kem_dec_s_key_dout,
        k_kem_dec_s_key_num_data_valid,
        k_kem_dec_s_key_fifo_cap,
        k_kem_dec_s_key_empty_n,
        k_kem_dec_s_key_read,
        act,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24,
        k_kem_dec_s_key_blk_n
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] p_read;
input  [63:0] p_read1;
input  [63:0] p_read2;
input  [63:0] p_read3;
input  [63:0] p_read4;
input  [63:0] p_read5;
input  [63:0] p_read6;
input  [63:0] p_read7;
input  [63:0] p_read8;
input  [63:0] p_read9;
input  [63:0] p_read10;
input  [63:0] p_read11;
input  [63:0] p_read12;
input  [63:0] p_read13;
input  [63:0] p_read14;
input  [63:0] p_read15;
input  [63:0] p_read16;
input  [63:0] p_read17;
input  [63:0] p_read18;
input  [63:0] p_read19;
input  [63:0] p_read20;
input  [63:0] p_read21;
input  [63:0] p_read22;
input  [63:0] p_read23;
input  [63:0] p_read24;
input  [263:0] k_kem_dec_s_key_dout;
input  [2:0] k_kem_dec_s_key_num_data_valid;
input  [2:0] k_kem_dec_s_key_fifo_cap;
input   k_kem_dec_s_key_empty_n;
output   k_kem_dec_s_key_read;
input  [0:0] act;
output  [63:0] ap_return_0;
output  [63:0] ap_return_1;
output  [63:0] ap_return_2;
output  [63:0] ap_return_3;
output  [63:0] ap_return_4;
output  [63:0] ap_return_5;
output  [63:0] ap_return_6;
output  [63:0] ap_return_7;
output  [63:0] ap_return_8;
output  [63:0] ap_return_9;
output  [63:0] ap_return_10;
output  [63:0] ap_return_11;
output  [63:0] ap_return_12;
output  [63:0] ap_return_13;
output  [63:0] ap_return_14;
output  [63:0] ap_return_15;
output  [63:0] ap_return_16;
output  [63:0] ap_return_17;
output  [63:0] ap_return_18;
output  [63:0] ap_return_19;
output  [63:0] ap_return_20;
output  [63:0] ap_return_21;
output  [63:0] ap_return_22;
output  [63:0] ap_return_23;
output  [63:0] ap_return_24;
output   k_kem_dec_s_key_blk_n;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg k_kem_dec_s_key_read;
reg[63:0] ap_return_0;
reg[63:0] ap_return_1;
reg[63:0] ap_return_2;
reg[63:0] ap_return_3;
reg[63:0] ap_return_4;
reg[63:0] ap_return_5;
reg[63:0] ap_return_6;
reg[63:0] ap_return_7;
reg[63:0] ap_return_8;
reg[63:0] ap_return_9;
reg[63:0] ap_return_10;
reg[63:0] ap_return_11;
reg[63:0] ap_return_12;
reg[63:0] ap_return_13;
reg[63:0] ap_return_14;
reg[63:0] ap_return_15;
reg[63:0] ap_return_16;
reg[63:0] ap_return_17;
reg[63:0] ap_return_18;
reg[63:0] ap_return_19;
reg[63:0] ap_return_20;
reg[63:0] ap_return_21;
reg[63:0] ap_return_22;
reg[63:0] ap_return_23;
reg[63:0] ap_return_24;
reg k_kem_dec_s_key_blk_n;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] act_read_read_fu_100_p2;
reg   [63:0] ap_phi_mux_phi_ln663_phi_fu_265_p4;
reg    ap_block_state1;
reg   [63:0] ap_phi_mux_phi_ln663_1_phi_fu_276_p4;
reg   [63:0] ap_phi_mux_phi_ln663_2_phi_fu_287_p4;
reg   [63:0] ap_phi_mux_phi_ln663_3_phi_fu_298_p4;
reg   [63:0] ap_phi_mux_phi_ln663_4_phi_fu_309_p4;
reg   [63:0] ap_phi_mux_phi_ln663_5_phi_fu_320_p4;
reg   [63:0] ap_phi_mux_phi_ln663_6_phi_fu_331_p4;
reg   [63:0] ap_phi_mux_phi_ln663_7_phi_fu_342_p4;
reg   [63:0] ap_phi_mux_phi_ln663_8_phi_fu_353_p4;
reg   [63:0] ap_phi_mux_phi_ln663_9_phi_fu_364_p4;
reg   [63:0] ap_phi_mux_phi_ln663_10_phi_fu_375_p4;
reg   [63:0] ap_phi_mux_phi_ln663_11_phi_fu_386_p4;
reg   [63:0] ap_phi_mux_phi_ln663_12_phi_fu_397_p4;
reg   [63:0] ap_phi_mux_phi_ln663_13_phi_fu_408_p4;
reg   [63:0] ap_phi_mux_phi_ln663_14_phi_fu_419_p4;
reg   [63:0] ap_phi_mux_phi_ln663_15_phi_fu_430_p4;
wire   [63:0] zext_ln662_fu_592_p1;
reg   [63:0] ap_phi_mux_phi_ln663_16_phi_fu_441_p4;
reg   [63:0] ap_phi_mux_phi_ln663_17_phi_fu_451_p4;
reg   [63:0] ap_phi_mux_phi_ln663_18_phi_fu_462_p4;
reg   [63:0] ap_phi_mux_phi_ln663_19_phi_fu_472_p4;
reg   [63:0] ap_phi_mux_phi_ln663_20_phi_fu_483_p4;
reg   [63:0] ap_phi_mux_phi_ln663_21_phi_fu_493_p4;
reg   [63:0] ap_phi_mux_phi_ln663_22_phi_fu_504_p4;
reg   [63:0] ap_phi_mux_phi_ln663_23_phi_fu_514_p4;
wire   [63:0] trunc_ln657_fu_532_p1;
reg   [63:0] ap_phi_mux_phi_ln663_24_phi_fu_525_p4;
wire   [7:0] tmp_1_fu_570_p4;
wire   [8:0] or_ln_fu_580_p3;
wire  signed [12:0] sext_ln662_fu_588_p1;
reg   [63:0] ap_return_0_preg;
reg   [63:0] ap_return_1_preg;
reg   [63:0] ap_return_2_preg;
reg   [63:0] ap_return_3_preg;
reg   [63:0] ap_return_4_preg;
reg   [63:0] ap_return_5_preg;
reg   [63:0] ap_return_6_preg;
reg   [63:0] ap_return_7_preg;
reg   [63:0] ap_return_8_preg;
reg   [63:0] ap_return_9_preg;
reg   [63:0] ap_return_10_preg;
reg   [63:0] ap_return_11_preg;
reg   [63:0] ap_return_12_preg;
reg   [63:0] ap_return_13_preg;
reg   [63:0] ap_return_14_preg;
reg   [63:0] ap_return_15_preg;
reg   [63:0] ap_return_16_preg;
reg   [63:0] ap_return_17_preg;
reg   [63:0] ap_return_18_preg;
reg   [63:0] ap_return_19_preg;
reg   [63:0] ap_return_20_preg;
reg   [63:0] ap_return_21_preg;
reg   [63:0] ap_return_22_preg;
reg   [63:0] ap_return_23_preg;
reg   [63:0] ap_return_24_preg;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_return_0_preg = 64'd0;
#0 ap_return_1_preg = 64'd0;
#0 ap_return_2_preg = 64'd0;
#0 ap_return_3_preg = 64'd0;
#0 ap_return_4_preg = 64'd0;
#0 ap_return_5_preg = 64'd0;
#0 ap_return_6_preg = 64'd0;
#0 ap_return_7_preg = 64'd0;
#0 ap_return_8_preg = 64'd0;
#0 ap_return_9_preg = 64'd0;
#0 ap_return_10_preg = 64'd0;
#0 ap_return_11_preg = 64'd0;
#0 ap_return_12_preg = 64'd0;
#0 ap_return_13_preg = 64'd0;
#0 ap_return_14_preg = 64'd0;
#0 ap_return_15_preg = 64'd0;
#0 ap_return_16_preg = 64'd0;
#0 ap_return_17_preg = 64'd0;
#0 ap_return_18_preg = 64'd0;
#0 ap_return_19_preg = 64'd0;
#0 ap_return_20_preg = 64'd0;
#0 ap_return_21_preg = 64'd0;
#0 ap_return_22_preg = 64'd0;
#0 ap_return_23_preg = 64'd0;
#0 ap_return_24_preg = 64'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 64'd0;
    end else begin
        if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_0_preg <= ap_phi_mux_phi_ln663_24_phi_fu_525_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_10_preg <= 64'd0;
    end else begin
        if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_10_preg <= ap_phi_mux_phi_ln663_7_phi_fu_342_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_11_preg <= 64'd0;
    end else begin
        if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_11_preg <= ap_phi_mux_phi_ln663_5_phi_fu_320_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_12_preg <= 64'd0;
    end else begin
        if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_12_preg <= ap_phi_mux_phi_ln663_4_phi_fu_309_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_13_preg <= 64'd0;
    end else begin
        if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_13_preg <= ap_phi_mux_phi_ln663_2_phi_fu_287_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_14_preg <= 64'd0;
    end else begin
        if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_14_preg <= ap_phi_mux_phi_ln663_1_phi_fu_276_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_15_preg <= 64'd0;
    end else begin
        if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_15_preg <= ap_phi_mux_phi_ln663_phi_fu_265_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_16_preg <= 64'd0;
    end else begin
        if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_16_preg <= ap_phi_mux_phi_ln663_3_phi_fu_298_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_17_preg <= 64'd0;
    end else begin
        if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_17_preg <= ap_phi_mux_phi_ln663_6_phi_fu_331_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_18_preg <= 64'd0;
    end else begin
        if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_18_preg <= ap_phi_mux_phi_ln663_9_phi_fu_364_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_19_preg <= 64'd0;
    end else begin
        if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_19_preg <= ap_phi_mux_phi_ln663_12_phi_fu_397_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 64'd0;
    end else begin
        if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_1_preg <= ap_phi_mux_phi_ln663_22_phi_fu_504_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_20_preg <= 64'd0;
    end else begin
        if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_20_preg <= ap_phi_mux_phi_ln663_15_phi_fu_430_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_21_preg <= 64'd0;
    end else begin
        if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_21_preg <= ap_phi_mux_phi_ln663_17_phi_fu_451_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_22_preg <= 64'd0;
    end else begin
        if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_22_preg <= ap_phi_mux_phi_ln663_19_phi_fu_472_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_23_preg <= 64'd0;
    end else begin
        if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_23_preg <= ap_phi_mux_phi_ln663_21_phi_fu_493_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_24_preg <= 64'd0;
    end else begin
        if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_24_preg <= ap_phi_mux_phi_ln663_23_phi_fu_514_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_2_preg <= 64'd0;
    end else begin
        if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_2_preg <= ap_phi_mux_phi_ln663_20_phi_fu_483_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_3_preg <= 64'd0;
    end else begin
        if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_3_preg <= ap_phi_mux_phi_ln663_18_phi_fu_462_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_4_preg <= 64'd0;
    end else begin
        if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_4_preg <= ap_phi_mux_phi_ln663_16_phi_fu_441_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_5_preg <= 64'd0;
    end else begin
        if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_5_preg <= ap_phi_mux_phi_ln663_14_phi_fu_419_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_6_preg <= 64'd0;
    end else begin
        if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_6_preg <= ap_phi_mux_phi_ln663_13_phi_fu_408_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_7_preg <= 64'd0;
    end else begin
        if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_7_preg <= ap_phi_mux_phi_ln663_11_phi_fu_386_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_8_preg <= 64'd0;
    end else begin
        if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_8_preg <= ap_phi_mux_phi_ln663_10_phi_fu_375_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_9_preg <= 64'd0;
    end else begin
        if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_9_preg <= ap_phi_mux_phi_ln663_8_phi_fu_353_p4;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((1'd0 == act_read_read_fu_100_p2)) begin
            ap_phi_mux_phi_ln663_10_phi_fu_375_p4 = p_read8;
        end else if ((1'd1 == act)) begin
            ap_phi_mux_phi_ln663_10_phi_fu_375_p4 = 64'd0;
        end else begin
            ap_phi_mux_phi_ln663_10_phi_fu_375_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_phi_ln663_10_phi_fu_375_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((1'd0 == act_read_read_fu_100_p2)) begin
            ap_phi_mux_phi_ln663_11_phi_fu_386_p4 = p_read7;
        end else if ((1'd1 == act)) begin
            ap_phi_mux_phi_ln663_11_phi_fu_386_p4 = 64'd0;
        end else begin
            ap_phi_mux_phi_ln663_11_phi_fu_386_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_phi_ln663_11_phi_fu_386_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((1'd0 == act_read_read_fu_100_p2)) begin
            ap_phi_mux_phi_ln663_12_phi_fu_397_p4 = p_read19;
        end else if ((1'd1 == act)) begin
            ap_phi_mux_phi_ln663_12_phi_fu_397_p4 = 64'd0;
        end else begin
            ap_phi_mux_phi_ln663_12_phi_fu_397_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_phi_ln663_12_phi_fu_397_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((1'd0 == act_read_read_fu_100_p2)) begin
            ap_phi_mux_phi_ln663_13_phi_fu_408_p4 = p_read6;
        end else if ((1'd1 == act)) begin
            ap_phi_mux_phi_ln663_13_phi_fu_408_p4 = 64'd0;
        end else begin
            ap_phi_mux_phi_ln663_13_phi_fu_408_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_phi_ln663_13_phi_fu_408_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((1'd0 == act_read_read_fu_100_p2)) begin
            ap_phi_mux_phi_ln663_14_phi_fu_419_p4 = p_read5;
        end else if ((1'd1 == act)) begin
            ap_phi_mux_phi_ln663_14_phi_fu_419_p4 = 64'd0;
        end else begin
            ap_phi_mux_phi_ln663_14_phi_fu_419_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_phi_ln663_14_phi_fu_419_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((1'd0 == act_read_read_fu_100_p2)) begin
            ap_phi_mux_phi_ln663_15_phi_fu_430_p4 = p_read20;
        end else if ((1'd1 == act)) begin
            ap_phi_mux_phi_ln663_15_phi_fu_430_p4 = 64'd0;
        end else begin
            ap_phi_mux_phi_ln663_15_phi_fu_430_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_phi_ln663_15_phi_fu_430_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((1'd0 == act_read_read_fu_100_p2)) begin
            ap_phi_mux_phi_ln663_16_phi_fu_441_p4 = p_read4;
        end else if ((1'd1 == act)) begin
            ap_phi_mux_phi_ln663_16_phi_fu_441_p4 = zext_ln662_fu_592_p1;
        end else begin
            ap_phi_mux_phi_ln663_16_phi_fu_441_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_phi_ln663_16_phi_fu_441_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((1'd0 == act_read_read_fu_100_p2)) begin
            ap_phi_mux_phi_ln663_17_phi_fu_451_p4 = p_read21;
        end else if ((1'd1 == act)) begin
            ap_phi_mux_phi_ln663_17_phi_fu_451_p4 = 64'd0;
        end else begin
            ap_phi_mux_phi_ln663_17_phi_fu_451_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_phi_ln663_17_phi_fu_451_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((1'd0 == act_read_read_fu_100_p2)) begin
            ap_phi_mux_phi_ln663_18_phi_fu_462_p4 = p_read3;
        end else if ((1'd1 == act)) begin
            ap_phi_mux_phi_ln663_18_phi_fu_462_p4 = {{k_kem_dec_s_key_dout[255:192]}};
        end else begin
            ap_phi_mux_phi_ln663_18_phi_fu_462_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_phi_ln663_18_phi_fu_462_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((1'd0 == act_read_read_fu_100_p2)) begin
            ap_phi_mux_phi_ln663_19_phi_fu_472_p4 = p_read22;
        end else if ((1'd1 == act)) begin
            ap_phi_mux_phi_ln663_19_phi_fu_472_p4 = 64'd0;
        end else begin
            ap_phi_mux_phi_ln663_19_phi_fu_472_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_phi_ln663_19_phi_fu_472_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((1'd0 == act_read_read_fu_100_p2)) begin
            ap_phi_mux_phi_ln663_1_phi_fu_276_p4 = p_read14;
        end else if ((1'd1 == act)) begin
            ap_phi_mux_phi_ln663_1_phi_fu_276_p4 = 64'd0;
        end else begin
            ap_phi_mux_phi_ln663_1_phi_fu_276_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_phi_ln663_1_phi_fu_276_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((1'd0 == act_read_read_fu_100_p2)) begin
            ap_phi_mux_phi_ln663_20_phi_fu_483_p4 = p_read2;
        end else if ((1'd1 == act)) begin
            ap_phi_mux_phi_ln663_20_phi_fu_483_p4 = {{k_kem_dec_s_key_dout[191:128]}};
        end else begin
            ap_phi_mux_phi_ln663_20_phi_fu_483_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_phi_ln663_20_phi_fu_483_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((1'd0 == act_read_read_fu_100_p2)) begin
            ap_phi_mux_phi_ln663_21_phi_fu_493_p4 = p_read23;
        end else if ((1'd1 == act)) begin
            ap_phi_mux_phi_ln663_21_phi_fu_493_p4 = 64'd0;
        end else begin
            ap_phi_mux_phi_ln663_21_phi_fu_493_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_phi_ln663_21_phi_fu_493_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((1'd0 == act_read_read_fu_100_p2)) begin
            ap_phi_mux_phi_ln663_22_phi_fu_504_p4 = p_read1;
        end else if ((1'd1 == act)) begin
            ap_phi_mux_phi_ln663_22_phi_fu_504_p4 = {{k_kem_dec_s_key_dout[127:64]}};
        end else begin
            ap_phi_mux_phi_ln663_22_phi_fu_504_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_phi_ln663_22_phi_fu_504_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((1'd0 == act_read_read_fu_100_p2)) begin
            ap_phi_mux_phi_ln663_23_phi_fu_514_p4 = p_read24;
        end else if ((1'd1 == act)) begin
            ap_phi_mux_phi_ln663_23_phi_fu_514_p4 = 64'd0;
        end else begin
            ap_phi_mux_phi_ln663_23_phi_fu_514_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_phi_ln663_23_phi_fu_514_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((1'd0 == act_read_read_fu_100_p2)) begin
            ap_phi_mux_phi_ln663_24_phi_fu_525_p4 = p_read;
        end else if ((1'd1 == act)) begin
            ap_phi_mux_phi_ln663_24_phi_fu_525_p4 = trunc_ln657_fu_532_p1;
        end else begin
            ap_phi_mux_phi_ln663_24_phi_fu_525_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_phi_ln663_24_phi_fu_525_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((1'd0 == act_read_read_fu_100_p2)) begin
            ap_phi_mux_phi_ln663_2_phi_fu_287_p4 = p_read13;
        end else if ((1'd1 == act)) begin
            ap_phi_mux_phi_ln663_2_phi_fu_287_p4 = 64'd0;
        end else begin
            ap_phi_mux_phi_ln663_2_phi_fu_287_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_phi_ln663_2_phi_fu_287_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((1'd0 == act_read_read_fu_100_p2)) begin
            ap_phi_mux_phi_ln663_3_phi_fu_298_p4 = p_read16;
        end else if ((1'd1 == act)) begin
            ap_phi_mux_phi_ln663_3_phi_fu_298_p4 = 64'd9223372036854775808;
        end else begin
            ap_phi_mux_phi_ln663_3_phi_fu_298_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_phi_ln663_3_phi_fu_298_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((1'd0 == act_read_read_fu_100_p2)) begin
            ap_phi_mux_phi_ln663_4_phi_fu_309_p4 = p_read12;
        end else if ((1'd1 == act)) begin
            ap_phi_mux_phi_ln663_4_phi_fu_309_p4 = 64'd0;
        end else begin
            ap_phi_mux_phi_ln663_4_phi_fu_309_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_phi_ln663_4_phi_fu_309_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((1'd0 == act_read_read_fu_100_p2)) begin
            ap_phi_mux_phi_ln663_5_phi_fu_320_p4 = p_read11;
        end else if ((1'd1 == act)) begin
            ap_phi_mux_phi_ln663_5_phi_fu_320_p4 = 64'd0;
        end else begin
            ap_phi_mux_phi_ln663_5_phi_fu_320_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_phi_ln663_5_phi_fu_320_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((1'd0 == act_read_read_fu_100_p2)) begin
            ap_phi_mux_phi_ln663_6_phi_fu_331_p4 = p_read17;
        end else if ((1'd1 == act)) begin
            ap_phi_mux_phi_ln663_6_phi_fu_331_p4 = 64'd0;
        end else begin
            ap_phi_mux_phi_ln663_6_phi_fu_331_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_phi_ln663_6_phi_fu_331_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((1'd0 == act_read_read_fu_100_p2)) begin
            ap_phi_mux_phi_ln663_7_phi_fu_342_p4 = p_read10;
        end else if ((1'd1 == act)) begin
            ap_phi_mux_phi_ln663_7_phi_fu_342_p4 = 64'd0;
        end else begin
            ap_phi_mux_phi_ln663_7_phi_fu_342_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_phi_ln663_7_phi_fu_342_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((1'd0 == act_read_read_fu_100_p2)) begin
            ap_phi_mux_phi_ln663_8_phi_fu_353_p4 = p_read9;
        end else if ((1'd1 == act)) begin
            ap_phi_mux_phi_ln663_8_phi_fu_353_p4 = 64'd0;
        end else begin
            ap_phi_mux_phi_ln663_8_phi_fu_353_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_phi_ln663_8_phi_fu_353_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((1'd0 == act_read_read_fu_100_p2)) begin
            ap_phi_mux_phi_ln663_9_phi_fu_364_p4 = p_read18;
        end else if ((1'd1 == act)) begin
            ap_phi_mux_phi_ln663_9_phi_fu_364_p4 = 64'd0;
        end else begin
            ap_phi_mux_phi_ln663_9_phi_fu_364_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_phi_ln663_9_phi_fu_364_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((1'd0 == act_read_read_fu_100_p2)) begin
            ap_phi_mux_phi_ln663_phi_fu_265_p4 = p_read15;
        end else if ((1'd1 == act)) begin
            ap_phi_mux_phi_ln663_phi_fu_265_p4 = 64'd0;
        end else begin
            ap_phi_mux_phi_ln663_phi_fu_265_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_phi_ln663_phi_fu_265_p4 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_0 = ap_phi_mux_phi_ln663_24_phi_fu_525_p4;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_1 = ap_phi_mux_phi_ln663_22_phi_fu_504_p4;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_10 = ap_phi_mux_phi_ln663_7_phi_fu_342_p4;
    end else begin
        ap_return_10 = ap_return_10_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_11 = ap_phi_mux_phi_ln663_5_phi_fu_320_p4;
    end else begin
        ap_return_11 = ap_return_11_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_12 = ap_phi_mux_phi_ln663_4_phi_fu_309_p4;
    end else begin
        ap_return_12 = ap_return_12_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_13 = ap_phi_mux_phi_ln663_2_phi_fu_287_p4;
    end else begin
        ap_return_13 = ap_return_13_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_14 = ap_phi_mux_phi_ln663_1_phi_fu_276_p4;
    end else begin
        ap_return_14 = ap_return_14_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_15 = ap_phi_mux_phi_ln663_phi_fu_265_p4;
    end else begin
        ap_return_15 = ap_return_15_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_16 = ap_phi_mux_phi_ln663_3_phi_fu_298_p4;
    end else begin
        ap_return_16 = ap_return_16_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_17 = ap_phi_mux_phi_ln663_6_phi_fu_331_p4;
    end else begin
        ap_return_17 = ap_return_17_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_18 = ap_phi_mux_phi_ln663_9_phi_fu_364_p4;
    end else begin
        ap_return_18 = ap_return_18_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_19 = ap_phi_mux_phi_ln663_12_phi_fu_397_p4;
    end else begin
        ap_return_19 = ap_return_19_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_2 = ap_phi_mux_phi_ln663_20_phi_fu_483_p4;
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_20 = ap_phi_mux_phi_ln663_15_phi_fu_430_p4;
    end else begin
        ap_return_20 = ap_return_20_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_21 = ap_phi_mux_phi_ln663_17_phi_fu_451_p4;
    end else begin
        ap_return_21 = ap_return_21_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_22 = ap_phi_mux_phi_ln663_19_phi_fu_472_p4;
    end else begin
        ap_return_22 = ap_return_22_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_23 = ap_phi_mux_phi_ln663_21_phi_fu_493_p4;
    end else begin
        ap_return_23 = ap_return_23_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_24 = ap_phi_mux_phi_ln663_23_phi_fu_514_p4;
    end else begin
        ap_return_24 = ap_return_24_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_3 = ap_phi_mux_phi_ln663_18_phi_fu_462_p4;
    end else begin
        ap_return_3 = ap_return_3_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_4 = ap_phi_mux_phi_ln663_16_phi_fu_441_p4;
    end else begin
        ap_return_4 = ap_return_4_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_5 = ap_phi_mux_phi_ln663_14_phi_fu_419_p4;
    end else begin
        ap_return_5 = ap_return_5_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_6 = ap_phi_mux_phi_ln663_13_phi_fu_408_p4;
    end else begin
        ap_return_6 = ap_return_6_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_7 = ap_phi_mux_phi_ln663_11_phi_fu_386_p4;
    end else begin
        ap_return_7 = ap_return_7_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_8 = ap_phi_mux_phi_ln663_10_phi_fu_375_p4;
    end else begin
        ap_return_8 = ap_return_8_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_9 = ap_phi_mux_phi_ln663_8_phi_fu_353_p4;
    end else begin
        ap_return_9 = ap_return_9_preg;
    end
end

always @ (*) begin
    if (((1'd1 == act) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        k_kem_dec_s_key_blk_n = k_kem_dec_s_key_empty_n;
    end else begin
        k_kem_dec_s_key_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'd1 == act) & (1'b1 == ap_CS_fsm_state1))) begin
        k_kem_dec_s_key_read = 1'b1;
    end else begin
        k_kem_dec_s_key_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign act_read_read_fu_100_p2 = act;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | ((1'd1 == act) & (k_kem_dec_s_key_empty_n == 1'b0)));
end

assign or_ln_fu_580_p3 = {{1'd1}, {tmp_1_fu_570_p4}};

assign sext_ln662_fu_588_p1 = $signed(or_ln_fu_580_p3);

assign tmp_1_fu_570_p4 = {{k_kem_dec_s_key_dout[263:256]}};

assign trunc_ln657_fu_532_p1 = k_kem_dec_s_key_dout[63:0];

assign zext_ln662_fu_592_p1 = $unsigned(sext_ln662_fu_588_p1);

endmodule //mlkem_accelerator_absorb
