// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mlkem_accelerator_invntt_layer_68 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        sinvl_3_0_dout,
        sinvl_3_0_num_data_valid,
        sinvl_3_0_fifo_cap,
        sinvl_3_0_empty_n,
        sinvl_3_0_read,
        sinvl_3_1_dout,
        sinvl_3_1_num_data_valid,
        sinvl_3_1_fifo_cap,
        sinvl_3_1_empty_n,
        sinvl_3_1_read,
        sinvl_4_0_din,
        sinvl_4_0_num_data_valid,
        sinvl_4_0_fifo_cap,
        sinvl_4_0_full_n,
        sinvl_4_0_write,
        sinvl_4_1_din,
        sinvl_4_1_num_data_valid,
        sinvl_4_1_fifo_cap,
        sinvl_4_1_full_n,
        sinvl_4_1_write,
        start_out,
        start_write
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] sinvl_3_0_dout;
input  [7:0] sinvl_3_0_num_data_valid;
input  [7:0] sinvl_3_0_fifo_cap;
input   sinvl_3_0_empty_n;
output   sinvl_3_0_read;
input  [15:0] sinvl_3_1_dout;
input  [7:0] sinvl_3_1_num_data_valid;
input  [7:0] sinvl_3_1_fifo_cap;
input   sinvl_3_1_empty_n;
output   sinvl_3_1_read;
output  [15:0] sinvl_4_0_din;
input  [7:0] sinvl_4_0_num_data_valid;
input  [7:0] sinvl_4_0_fifo_cap;
input   sinvl_4_0_full_n;
output   sinvl_4_0_write;
output  [15:0] sinvl_4_1_din;
input  [7:0] sinvl_4_1_num_data_valid;
input  [7:0] sinvl_4_1_fifo_cap;
input   sinvl_4_1_full_n;
output   sinvl_4_1_write;
output   start_out;
output   start_write;

reg ap_idle;
reg sinvl_3_0_read;
reg sinvl_3_1_read;
reg sinvl_4_0_write;
reg sinvl_4_1_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    internal_ap_ready;
wire    ap_CS_fsm_pp0_stage1;
reg   [0:0] icmp_ln1454_reg_311;
reg   [0:0] tmp_reg_315;
reg    ap_predicate_op48_read_state2;
reg    ap_predicate_op49_read_state2;
reg    ap_block_state2_pp0_stage1_iter0;
reg    ap_block_state10_pp0_stage1_iter4;
reg    ap_block_pp0_stage1_subdone;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [6:0] zetas43_address0;
reg    zetas43_ce0;
wire   [11:0] zetas43_q0;
reg    sinvl_3_0_blk_n;
wire    ap_block_pp0_stage1;
wire    ap_block_pp0_stage0;
reg    sinvl_3_1_blk_n;
reg    sinvl_4_0_blk_n;
reg    sinvl_4_1_blk_n;
wire   [0:0] icmp_ln1454_fu_150_p2;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_predicate_op54_read_state3;
reg    ap_predicate_op56_read_state3;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [31:0] index_7_fu_173_p2;
reg   [31:0] index_7_reg_319;
reg   [15:0] wing1_38_reg_330;
reg    ap_block_pp0_stage1_11001;
reg   [15:0] wing1_reg_335;
reg  signed [11:0] zetas43_load_reg_340;
(* use_dsp48 = "no" *) wire  signed [15:0] sum_fu_202_p2;
reg  signed [15:0] sum_reg_345;
reg  signed [15:0] sum_reg_345_pp0_iter2_reg;
reg  signed [15:0] sum_reg_345_pp0_iter3_reg;
wire   [15:0] sub_ln1444_fu_208_p2;
reg  signed [15:0] sub_ln1444_reg_351;
wire  signed [27:0] pr_fu_223_p2;
reg  signed [27:0] pr_reg_361;
reg  signed [27:0] pr_reg_361_pp0_iter2_reg;
wire  signed [15:0] trunc_ln1374_fu_229_p1;
reg  signed [15:0] trunc_ln1374_reg_366;
reg   [12:0] t_42_reg_386;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [15:0] ap_phi_mux_wing2_35_phi_fu_120_p4;
wire   [15:0] ap_phi_reg_pp0_iter1_wing2_35_reg_117;
reg   [15:0] ap_phi_mux_wing1_41_phi_fu_131_p4;
wire   [15:0] ap_phi_reg_pp0_iter1_wing1_41_reg_128;
reg   [31:0] index_fu_70;
wire   [31:0] index_8_fu_190_p3;
wire    ap_loop_init;
reg   [31:0] ap_sig_allocacmp_index_load;
reg   [8:0] i_fu_74;
wire   [8:0] i_129_fu_156_p2;
reg   [8:0] ap_sig_allocacmp_i_128;
wire  signed [15:0] grp_fu_289_p3;
reg    ap_block_pp0_stage1_01001;
wire   [0:0] icmp_ln1470_fu_185_p2;
wire  signed [12:0] t_fu_233_p1;
wire  signed [15:0] t_fu_233_p2;
wire  signed [30:0] trunc_ln_fu_242_p1;
wire   [30:0] grp_fu_271_p3;
wire  signed [4:0] trunc_ln_fu_242_p4;
wire  signed [28:0] grp_fu_280_p3;
wire   [14:0] grp_fu_271_p1;
wire   [25:0] grp_fu_271_p2;
wire  signed [12:0] grp_fu_280_p1;
wire  signed [12:0] grp_fu_289_p1;
reg    grp_fu_271_ce;
reg    grp_fu_280_ce;
reg    grp_fu_289_ce;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [1:0] ap_NS_fsm;
reg    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to4;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_251;
reg    ap_condition_431;
reg    ap_condition_434;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 index_fu_70 = 32'd0;
#0 i_fu_74 = 9'd0;
end

mlkem_accelerator_ntt_layer_2_zetas49_ROM_AUTO_1R #(
    .DataWidth( 12 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
zetas43_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(zetas43_address0),
    .ce0(zetas43_ce0),
    .q0(zetas43_q0)
);

mlkem_accelerator_mul_16s_12s_28_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 28 ))
mul_16s_12s_28_1_1_U1702(
    .din0(sub_ln1444_reg_351),
    .din1(zetas43_load_reg_340),
    .dout(pr_fu_223_p2)
);

mlkem_accelerator_mul_16s_13s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 16 ))
mul_16s_13s_16_1_1_U1703(
    .din0(trunc_ln1374_reg_366),
    .din1(t_fu_233_p1),
    .dout(t_fu_233_p2)
);

mlkem_accelerator_mac_muladd_16s_15ns_26ns_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 31 ))
mac_muladd_16s_15ns_26ns_31_4_1_U1704(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sum_reg_345),
    .din1(grp_fu_271_p1),
    .din2(grp_fu_271_p2),
    .ce(grp_fu_271_ce),
    .dout(grp_fu_271_p3)
);

mlkem_accelerator_mac_muladd_16s_13s_28s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 28 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_13s_28s_29_4_1_U1705(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(t_fu_233_p2),
    .din1(grp_fu_280_p1),
    .din2(pr_reg_361_pp0_iter2_reg),
    .ce(grp_fu_280_ce),
    .dout(grp_fu_280_p3)
);

mlkem_accelerator_mac_muladd_5s_13s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_5s_13s_16s_16_4_1_U1706(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trunc_ln_fu_242_p4),
    .din1(grp_fu_289_p1),
    .din2(sum_reg_345_pp0_iter3_reg),
    .ce(grp_fu_289_ce),
    .dout(grp_fu_289_p3)
);

mlkem_accelerator_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_251)) begin
        if ((icmp_ln1454_fu_150_p2 == 1'd0)) begin
            i_fu_74 <= i_129_fu_156_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_74 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if ((1'b1 == ap_condition_434)) begin
            index_fu_70 <= 32'd16;
        end else if ((1'b1 == ap_condition_431)) begin
            index_fu_70 <= index_8_fu_190_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        pr_reg_361 <= pr_fu_223_p2;
        pr_reg_361_pp0_iter2_reg <= pr_reg_361;
        t_42_reg_386 <= {{grp_fu_280_p3[28:16]}};
        trunc_ln1374_reg_366 <= trunc_ln1374_fu_229_p1;
        zetas43_load_reg_340 <= zetas43_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln1454_reg_311 <= icmp_ln1454_fu_150_p2;
        index_7_reg_319 <= index_7_fu_173_p2;
        sub_ln1444_reg_351 <= sub_ln1444_fu_208_p2;
        sum_reg_345 <= sum_fu_202_p2;
        sum_reg_345_pp0_iter2_reg <= sum_reg_345;
        sum_reg_345_pp0_iter3_reg <= sum_reg_345_pp0_iter2_reg;
        tmp_reg_315 <= ap_sig_allocacmp_i_128[32'd6];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        wing1_38_reg_330 <= sinvl_3_0_dout;
        wing1_reg_335 <= sinvl_3_1_dout;
    end
end

always @ (*) begin
    if (((icmp_ln1454_reg_311 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to4 = 1'b1;
    end else begin
        ap_idle_pp0_1to4 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln1454_reg_311 == 1'd0)) begin
        if ((tmp_reg_315 == 1'd1)) begin
            ap_phi_mux_wing1_41_phi_fu_131_p4 = wing1_reg_335;
        end else if ((tmp_reg_315 == 1'd0)) begin
            ap_phi_mux_wing1_41_phi_fu_131_p4 = wing1_38_reg_330;
        end else begin
            ap_phi_mux_wing1_41_phi_fu_131_p4 = ap_phi_reg_pp0_iter1_wing1_41_reg_128;
        end
    end else begin
        ap_phi_mux_wing1_41_phi_fu_131_p4 = ap_phi_reg_pp0_iter1_wing1_41_reg_128;
    end
end

always @ (*) begin
    if ((icmp_ln1454_reg_311 == 1'd0)) begin
        if ((tmp_reg_315 == 1'd1)) begin
            ap_phi_mux_wing2_35_phi_fu_120_p4 = sinvl_3_1_dout;
        end else if ((tmp_reg_315 == 1'd0)) begin
            ap_phi_mux_wing2_35_phi_fu_120_p4 = sinvl_3_0_dout;
        end else begin
            ap_phi_mux_wing2_35_phi_fu_120_p4 = ap_phi_reg_pp0_iter1_wing2_35_reg_117;
        end
    end else begin
        ap_phi_mux_wing2_35_phi_fu_120_p4 = ap_phi_reg_pp0_iter1_wing2_35_reg_117;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_i_128 = 9'd0;
    end else begin
        ap_sig_allocacmp_i_128 = i_fu_74;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_index_load = 32'd16;
    end else begin
        ap_sig_allocacmp_index_load = index_fu_70;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_271_ce = 1'b1;
    end else begin
        grp_fu_271_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_280_ce = 1'b1;
    end else begin
        grp_fu_280_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_289_ce = 1'b1;
    end else begin
        grp_fu_289_ce = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((((ap_predicate_op48_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((tmp_reg_315 == 1'd0) & (icmp_ln1454_reg_311 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)))) begin
        sinvl_3_0_blk_n = sinvl_3_0_empty_n;
    end else begin
        sinvl_3_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_predicate_op48_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op54_read_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        sinvl_3_0_read = 1'b1;
    end else begin
        sinvl_3_0_read = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_op49_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((tmp_reg_315 == 1'd1) & (icmp_ln1454_reg_311 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)))) begin
        sinvl_3_1_blk_n = sinvl_3_1_empty_n;
    end else begin
        sinvl_3_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_predicate_op49_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op56_read_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        sinvl_3_1_read = 1'b1;
    end else begin
        sinvl_3_1_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        sinvl_4_0_blk_n = sinvl_4_0_full_n;
    end else begin
        sinvl_4_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        sinvl_4_0_write = 1'b1;
    end else begin
        sinvl_4_0_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        sinvl_4_1_blk_n = sinvl_4_1_full_n;
    end else begin
        sinvl_4_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        sinvl_4_1_write = 1'b1;
    end else begin
        sinvl_4_1_write = 1'b0;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        zetas43_ce0 = 1'b1;
    end else begin
        zetas43_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to4 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter1)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001 = (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage1_iter4)));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage1_iter4)));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage1_iter4)));
end

always @ (*) begin
    ap_block_state10_pp0_stage1_iter4 = ((sinvl_4_1_full_n == 1'b0) | (sinvl_4_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0 = (((ap_predicate_op49_read_state2 == 1'b1) & (sinvl_3_1_empty_n == 1'b0)) | ((ap_predicate_op48_read_state2 == 1'b1) & (sinvl_3_0_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = (((sinvl_3_1_empty_n == 1'b0) & (ap_predicate_op56_read_state3 == 1'b1)) | ((sinvl_3_0_empty_n == 1'b0) & (ap_predicate_op54_read_state3 == 1'b1)));
end

always @ (*) begin
    ap_condition_251 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

always @ (*) begin
    ap_condition_431 = ((icmp_ln1454_reg_311 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001));
end

always @ (*) begin
    ap_condition_434 = ((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_phi_reg_pp0_iter1_wing1_41_reg_128 = 'bx;

assign ap_phi_reg_pp0_iter1_wing2_35_reg_117 = 'bx;

always @ (*) begin
    ap_predicate_op48_read_state2 = ((tmp_reg_315 == 1'd0) & (icmp_ln1454_reg_311 == 1'd0));
end

always @ (*) begin
    ap_predicate_op49_read_state2 = ((tmp_reg_315 == 1'd1) & (icmp_ln1454_reg_311 == 1'd0));
end

always @ (*) begin
    ap_predicate_op54_read_state3 = ((tmp_reg_315 == 1'd0) & (icmp_ln1454_reg_311 == 1'd0));
end

always @ (*) begin
    ap_predicate_op56_read_state3 = ((tmp_reg_315 == 1'd1) & (icmp_ln1454_reg_311 == 1'd0));
end

assign ap_ready = internal_ap_ready;

assign grp_fu_271_p1 = 31'd20159;

assign grp_fu_271_p2 = 31'd33554432;

assign grp_fu_280_p1 = 29'd536867583;

assign grp_fu_289_p1 = 16'd62207;

assign i_129_fu_156_p2 = (ap_sig_allocacmp_i_128 + 9'd1);

assign icmp_ln1454_fu_150_p2 = ((ap_sig_allocacmp_i_128 == 9'd384) ? 1'b1 : 1'b0);

assign icmp_ln1470_fu_185_p2 = ((index_7_reg_319 == 32'd8) ? 1'b1 : 1'b0);

assign index_7_fu_173_p2 = ($signed(ap_sig_allocacmp_index_load) + $signed(32'd4294967295));

assign index_8_fu_190_p3 = ((icmp_ln1470_fu_185_p2[0:0] == 1'b1) ? 32'd16 : index_7_reg_319);

assign sinvl_4_0_din = grp_fu_289_p3;

assign sinvl_4_1_din = $signed(t_42_reg_386);

assign start_out = real_start;

assign sub_ln1444_fu_208_p2 = (ap_phi_mux_wing2_35_phi_fu_120_p4 - ap_phi_mux_wing1_41_phi_fu_131_p4);

assign sum_fu_202_p2 = (ap_phi_mux_wing1_41_phi_fu_131_p4 + ap_phi_mux_wing2_35_phi_fu_120_p4);

assign t_fu_233_p1 = 16'd62209;

assign trunc_ln1374_fu_229_p1 = pr_fu_223_p2[15:0];

assign trunc_ln_fu_242_p1 = grp_fu_271_p3;

assign trunc_ln_fu_242_p4 = {{trunc_ln_fu_242_p1[30:26]}};

assign zetas43_address0 = index_7_fu_173_p2;

endmodule //mlkem_accelerator_invntt_layer_68
