// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mlkem_accelerator_sha (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        s_buf_sha_dout,
        s_buf_sha_num_data_valid,
        s_buf_sha_fifo_cap,
        s_buf_sha_empty_n,
        s_buf_sha_read,
        s_kr_orig_1_din,
        s_kr_orig_1_num_data_valid,
        s_kr_orig_1_fifo_cap,
        s_kr_orig_1_full_n,
        s_kr_orig_1_write
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [7:0] s_buf_sha_dout;
input  [8:0] s_buf_sha_num_data_valid;
input  [8:0] s_buf_sha_fifo_cap;
input   s_buf_sha_empty_n;
output   s_buf_sha_read;
output  [7:0] s_kr_orig_1_din;
input  [7:0] s_kr_orig_1_num_data_valid;
input  [7:0] s_kr_orig_1_fifo_cap;
input   s_kr_orig_1_full_n;
output   s_kr_orig_1_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg s_buf_sha_read;
reg s_kr_orig_1_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg   [63:0] s_reg_274;
wire    ap_CS_fsm_state4;
wire    grp_KeccakF1600_StatePermute_fu_76_ap_done;
reg   [63:0] s_8_reg_279;
reg   [63:0] s_9_reg_284;
reg   [63:0] s_10_reg_289;
reg   [63:0] s_11_reg_294;
reg   [63:0] s_12_reg_299;
reg   [63:0] s_13_reg_304;
reg   [63:0] s_14_reg_309;
wire    grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_ap_start;
wire    grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_ap_done;
wire    grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_ap_idle;
wire    grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_ap_ready;
wire    grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_buf_sha_read;
wire   [63:0] grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_22_out;
wire    grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_22_out_ap_vld;
wire   [63:0] grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_21_out;
wire    grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_21_out_ap_vld;
wire   [63:0] grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_20_out;
wire    grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_20_out_ap_vld;
wire   [63:0] grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_19_out;
wire    grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_19_out_ap_vld;
wire   [63:0] grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_18_out;
wire    grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_18_out_ap_vld;
wire   [63:0] grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_17_out;
wire    grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_17_out_ap_vld;
wire   [63:0] grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_16_out;
wire    grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_16_out_ap_vld;
wire   [63:0] grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_out;
wire    grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_out_ap_vld;
wire    grp_KeccakF1600_StatePermute_fu_76_ap_start;
wire    grp_KeccakF1600_StatePermute_fu_76_ap_idle;
wire    grp_KeccakF1600_StatePermute_fu_76_ap_ready;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_76_ap_return_0;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_76_ap_return_1;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_76_ap_return_2;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_76_ap_return_3;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_76_ap_return_4;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_76_ap_return_5;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_76_ap_return_6;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_76_ap_return_7;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_76_ap_return_8;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_76_ap_return_9;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_76_ap_return_10;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_76_ap_return_11;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_76_ap_return_12;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_76_ap_return_13;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_76_ap_return_14;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_76_ap_return_15;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_76_ap_return_16;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_76_ap_return_17;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_76_ap_return_18;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_76_ap_return_19;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_76_ap_return_20;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_76_ap_return_21;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_76_ap_return_22;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_76_ap_return_23;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_76_ap_return_24;
wire    grp_sha_Pipeline_VITIS_LOOP_602_5_VITIS_LOOP_603_6_fu_124_ap_start;
wire    grp_sha_Pipeline_VITIS_LOOP_602_5_VITIS_LOOP_603_6_fu_124_ap_done;
wire    grp_sha_Pipeline_VITIS_LOOP_602_5_VITIS_LOOP_603_6_fu_124_ap_idle;
wire    grp_sha_Pipeline_VITIS_LOOP_602_5_VITIS_LOOP_603_6_fu_124_ap_ready;
wire   [7:0] grp_sha_Pipeline_VITIS_LOOP_602_5_VITIS_LOOP_603_6_fu_124_s_kr_orig_1_din;
wire    grp_sha_Pipeline_VITIS_LOOP_602_5_VITIS_LOOP_603_6_fu_124_s_kr_orig_1_write;
reg    grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_ap_start_reg;
reg    ap_block_state1_ignore_call17;
wire    ap_CS_fsm_state2;
reg    grp_KeccakF1600_StatePermute_fu_76_ap_start_reg;
wire    ap_CS_fsm_state3;
reg    grp_sha_Pipeline_VITIS_LOOP_602_5_VITIS_LOOP_603_6_fu_124_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg   [5:0] ap_NS_fsm;
reg    ap_block_state1;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 6'd1;
#0 grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_ap_start_reg = 1'b0;
#0 grp_KeccakF1600_StatePermute_fu_76_ap_start_reg = 1'b0;
#0 grp_sha_Pipeline_VITIS_LOOP_602_5_VITIS_LOOP_603_6_fu_124_ap_start_reg = 1'b0;
end

mlkem_accelerator_sha_Pipeline_VITIS_LOOP_595_4 grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_ap_start),
    .ap_done(grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_ap_done),
    .ap_idle(grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_ap_idle),
    .ap_ready(grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_ap_ready),
    .s_buf_sha_dout(s_buf_sha_dout),
    .s_buf_sha_num_data_valid(9'd0),
    .s_buf_sha_fifo_cap(9'd0),
    .s_buf_sha_empty_n(s_buf_sha_empty_n),
    .s_buf_sha_read(grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_buf_sha_read),
    .s_22_out(grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_22_out),
    .s_22_out_ap_vld(grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_22_out_ap_vld),
    .s_21_out(grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_21_out),
    .s_21_out_ap_vld(grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_21_out_ap_vld),
    .s_20_out(grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_20_out),
    .s_20_out_ap_vld(grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_20_out_ap_vld),
    .s_19_out(grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_19_out),
    .s_19_out_ap_vld(grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_19_out_ap_vld),
    .s_18_out(grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_18_out),
    .s_18_out_ap_vld(grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_18_out_ap_vld),
    .s_17_out(grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_17_out),
    .s_17_out_ap_vld(grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_17_out_ap_vld),
    .s_16_out(grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_16_out),
    .s_16_out_ap_vld(grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_16_out_ap_vld),
    .s_out(grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_out),
    .s_out_ap_vld(grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_out_ap_vld)
);

mlkem_accelerator_KeccakF1600_StatePermute grp_KeccakF1600_StatePermute_fu_76(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_KeccakF1600_StatePermute_fu_76_ap_start),
    .ap_done(grp_KeccakF1600_StatePermute_fu_76_ap_done),
    .ap_idle(grp_KeccakF1600_StatePermute_fu_76_ap_idle),
    .ap_ready(grp_KeccakF1600_StatePermute_fu_76_ap_ready),
    .state_read(grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_out),
    .state_read_49(grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_16_out),
    .state_read_50(grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_17_out),
    .state_read_51(grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_18_out),
    .state_read_52(grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_19_out),
    .state_read_53(grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_20_out),
    .state_read_54(grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_21_out),
    .state_read_55(grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_22_out),
    .state_read_56(64'd9223372036854775814),
    .state_read_57(64'd0),
    .state_read_58(64'd0),
    .state_read_59(64'd0),
    .state_read_60(64'd0),
    .state_read_61(64'd0),
    .state_read_62(64'd0),
    .state_read_63(64'd0),
    .state_read_64(64'd0),
    .state_read_65(64'd0),
    .state_read_66(64'd0),
    .state_read_67(64'd0),
    .state_read_68(64'd0),
    .state_read_69(64'd0),
    .state_read_70(64'd0),
    .state_read_71(64'd0),
    .state_read_72(64'd0),
    .ap_return_0(grp_KeccakF1600_StatePermute_fu_76_ap_return_0),
    .ap_return_1(grp_KeccakF1600_StatePermute_fu_76_ap_return_1),
    .ap_return_2(grp_KeccakF1600_StatePermute_fu_76_ap_return_2),
    .ap_return_3(grp_KeccakF1600_StatePermute_fu_76_ap_return_3),
    .ap_return_4(grp_KeccakF1600_StatePermute_fu_76_ap_return_4),
    .ap_return_5(grp_KeccakF1600_StatePermute_fu_76_ap_return_5),
    .ap_return_6(grp_KeccakF1600_StatePermute_fu_76_ap_return_6),
    .ap_return_7(grp_KeccakF1600_StatePermute_fu_76_ap_return_7),
    .ap_return_8(grp_KeccakF1600_StatePermute_fu_76_ap_return_8),
    .ap_return_9(grp_KeccakF1600_StatePermute_fu_76_ap_return_9),
    .ap_return_10(grp_KeccakF1600_StatePermute_fu_76_ap_return_10),
    .ap_return_11(grp_KeccakF1600_StatePermute_fu_76_ap_return_11),
    .ap_return_12(grp_KeccakF1600_StatePermute_fu_76_ap_return_12),
    .ap_return_13(grp_KeccakF1600_StatePermute_fu_76_ap_return_13),
    .ap_return_14(grp_KeccakF1600_StatePermute_fu_76_ap_return_14),
    .ap_return_15(grp_KeccakF1600_StatePermute_fu_76_ap_return_15),
    .ap_return_16(grp_KeccakF1600_StatePermute_fu_76_ap_return_16),
    .ap_return_17(grp_KeccakF1600_StatePermute_fu_76_ap_return_17),
    .ap_return_18(grp_KeccakF1600_StatePermute_fu_76_ap_return_18),
    .ap_return_19(grp_KeccakF1600_StatePermute_fu_76_ap_return_19),
    .ap_return_20(grp_KeccakF1600_StatePermute_fu_76_ap_return_20),
    .ap_return_21(grp_KeccakF1600_StatePermute_fu_76_ap_return_21),
    .ap_return_22(grp_KeccakF1600_StatePermute_fu_76_ap_return_22),
    .ap_return_23(grp_KeccakF1600_StatePermute_fu_76_ap_return_23),
    .ap_return_24(grp_KeccakF1600_StatePermute_fu_76_ap_return_24)
);

mlkem_accelerator_sha_Pipeline_VITIS_LOOP_602_5_VITIS_LOOP_603_6 grp_sha_Pipeline_VITIS_LOOP_602_5_VITIS_LOOP_603_6_fu_124(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sha_Pipeline_VITIS_LOOP_602_5_VITIS_LOOP_603_6_fu_124_ap_start),
    .ap_done(grp_sha_Pipeline_VITIS_LOOP_602_5_VITIS_LOOP_603_6_fu_124_ap_done),
    .ap_idle(grp_sha_Pipeline_VITIS_LOOP_602_5_VITIS_LOOP_603_6_fu_124_ap_idle),
    .ap_ready(grp_sha_Pipeline_VITIS_LOOP_602_5_VITIS_LOOP_603_6_fu_124_ap_ready),
    .s_kr_orig_1_din(grp_sha_Pipeline_VITIS_LOOP_602_5_VITIS_LOOP_603_6_fu_124_s_kr_orig_1_din),
    .s_kr_orig_1_num_data_valid(8'd0),
    .s_kr_orig_1_fifo_cap(8'd0),
    .s_kr_orig_1_full_n(s_kr_orig_1_full_n),
    .s_kr_orig_1_write(grp_sha_Pipeline_VITIS_LOOP_602_5_VITIS_LOOP_603_6_fu_124_s_kr_orig_1_write),
    .s_23(s_reg_274),
    .s_24(s_8_reg_279),
    .s_25(s_9_reg_284),
    .s_26(s_10_reg_289),
    .s_27(s_11_reg_294),
    .s_28(s_12_reg_299),
    .s_29(s_13_reg_304),
    .s_30(s_14_reg_309)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state6) & (grp_sha_Pipeline_VITIS_LOOP_602_5_VITIS_LOOP_603_6_fu_124_ap_done == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_KeccakF1600_StatePermute_fu_76_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_KeccakF1600_StatePermute_fu_76_ap_start_reg <= 1'b1;
        end else if ((grp_KeccakF1600_StatePermute_fu_76_ap_ready == 1'b1)) begin
            grp_KeccakF1600_StatePermute_fu_76_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1_ignore_call17))) begin
            grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_ap_start_reg <= 1'b1;
        end else if ((grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_ap_ready == 1'b1)) begin
            grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sha_Pipeline_VITIS_LOOP_602_5_VITIS_LOOP_603_6_fu_124_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_sha_Pipeline_VITIS_LOOP_602_5_VITIS_LOOP_603_6_fu_124_ap_start_reg <= 1'b1;
        end else if ((grp_sha_Pipeline_VITIS_LOOP_602_5_VITIS_LOOP_603_6_fu_124_ap_ready == 1'b1)) begin
            grp_sha_Pipeline_VITIS_LOOP_602_5_VITIS_LOOP_603_6_fu_124_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_KeccakF1600_StatePermute_fu_76_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        s_10_reg_289 <= grp_KeccakF1600_StatePermute_fu_76_ap_return_3;
        s_11_reg_294 <= grp_KeccakF1600_StatePermute_fu_76_ap_return_4;
        s_12_reg_299 <= grp_KeccakF1600_StatePermute_fu_76_ap_return_5;
        s_13_reg_304 <= grp_KeccakF1600_StatePermute_fu_76_ap_return_6;
        s_14_reg_309 <= grp_KeccakF1600_StatePermute_fu_76_ap_return_7;
        s_8_reg_279 <= grp_KeccakF1600_StatePermute_fu_76_ap_return_1;
        s_9_reg_284 <= grp_KeccakF1600_StatePermute_fu_76_ap_return_2;
        s_reg_274 <= grp_KeccakF1600_StatePermute_fu_76_ap_return_0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_KeccakF1600_StatePermute_fu_76_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_sha_Pipeline_VITIS_LOOP_602_5_VITIS_LOOP_603_6_fu_124_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_sha_Pipeline_VITIS_LOOP_602_5_VITIS_LOOP_603_6_fu_124_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_sha_Pipeline_VITIS_LOOP_602_5_VITIS_LOOP_603_6_fu_124_ap_done == 1'b1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        s_buf_sha_read = grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_s_buf_sha_read;
    end else begin
        s_buf_sha_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        s_kr_orig_1_write = grp_sha_Pipeline_VITIS_LOOP_602_5_VITIS_LOOP_603_6_fu_124_s_kr_orig_1_write;
    end else begin
        s_kr_orig_1_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_KeccakF1600_StatePermute_fu_76_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_sha_Pipeline_VITIS_LOOP_602_5_VITIS_LOOP_603_6_fu_124_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call17 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign grp_KeccakF1600_StatePermute_fu_76_ap_start = grp_KeccakF1600_StatePermute_fu_76_ap_start_reg;

assign grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_ap_start = grp_sha_Pipeline_VITIS_LOOP_595_4_fu_62_ap_start_reg;

assign grp_sha_Pipeline_VITIS_LOOP_602_5_VITIS_LOOP_603_6_fu_124_ap_start = grp_sha_Pipeline_VITIS_LOOP_602_5_VITIS_LOOP_603_6_fu_124_ap_start_reg;

assign s_kr_orig_1_din = grp_sha_Pipeline_VITIS_LOOP_602_5_VITIS_LOOP_603_6_fu_124_s_kr_orig_1_din;

assign start_out = real_start;

endmodule //mlkem_accelerator_sha
