// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mlkem_accelerator_split_short_64 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        s_basemul_add_dout,
        s_basemul_add_num_data_valid,
        s_basemul_add_fifo_cap,
        s_basemul_add_empty_n,
        s_basemul_add_read,
        sinvl_0_1_din,
        sinvl_0_1_num_data_valid,
        sinvl_0_1_fifo_cap,
        sinvl_0_1_full_n,
        sinvl_0_1_write,
        sinvl_0_0_din,
        sinvl_0_0_num_data_valid,
        sinvl_0_0_fifo_cap,
        sinvl_0_0_full_n,
        sinvl_0_0_write,
        start_out,
        start_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] s_basemul_add_dout;
input  [7:0] s_basemul_add_num_data_valid;
input  [7:0] s_basemul_add_fifo_cap;
input   s_basemul_add_empty_n;
output   s_basemul_add_read;
output  [15:0] sinvl_0_1_din;
input  [7:0] sinvl_0_1_num_data_valid;
input  [7:0] sinvl_0_1_fifo_cap;
input   sinvl_0_1_full_n;
output   sinvl_0_1_write;
output  [15:0] sinvl_0_0_din;
input  [7:0] sinvl_0_0_num_data_valid;
input  [7:0] sinvl_0_0_fifo_cap;
input   sinvl_0_0_full_n;
output   sinvl_0_0_write;
output   start_out;
output   start_write;

reg ap_idle;
reg s_basemul_add_read;
reg sinvl_0_1_write;
reg sinvl_0_0_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] icmp_ln989_reg_155;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln987_fu_92_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    s_basemul_add_blk_n;
wire    ap_block_pp0_stage0;
reg    sinvl_0_0_blk_n;
reg    sinvl_0_1_blk_n;
wire   [0:0] icmp_ln989_fu_104_p2;
reg    ap_block_pp0_stage0_11001;
wire   [31:0] grp_fu_70_p2;
reg   [31:0] counter_18_reg_159;
wire   [0:0] icmp_ln996_fu_110_p2;
reg   [0:0] icmp_ln996_reg_164;
reg   [31:0] counter_fu_40;
wire   [31:0] counter_19_fu_126_p3;
reg   [31:0] ap_sig_allocacmp_counter_16;
wire    ap_loop_init;
reg   [9:0] i_fu_44;
wire   [9:0] i_32_fu_98_p2;
reg   [9:0] ap_sig_allocacmp_i_31;
reg    ap_block_pp0_stage0_01001;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_213;
reg    ap_condition_116;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 counter_fu_40 = 32'd0;
#0 i_fu_44 = 10'd0;
end

mlkem_accelerator_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((1'b1 == ap_condition_213)) begin
            counter_fu_40 <= grp_fu_70_p2;
        end else if (((ap_start_int == 1'b1) & (ap_loop_init == 1'b1))) begin
            counter_fu_40 <= 32'd0;
        end else if (((icmp_ln989_reg_155 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            counter_fu_40 <= counter_19_fu_126_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_116)) begin
        if ((icmp_ln987_fu_92_p2 == 1'd0)) begin
            i_fu_44 <= i_32_fu_98_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_44 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        counter_18_reg_159 <= grp_fu_70_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln989_reg_155 <= icmp_ln989_fu_104_p2;
        icmp_ln996_reg_164 <= icmp_ln996_fu_110_p2;
    end
end

always @ (*) begin
    if (((icmp_ln987_fu_92_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_start_int == 1'b1) & (ap_loop_init == 1'b1))) begin
            ap_sig_allocacmp_counter_16 = 32'd0;
        end else if (((icmp_ln989_reg_155 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            ap_sig_allocacmp_counter_16 = counter_19_fu_126_p3;
        end else begin
            ap_sig_allocacmp_counter_16 = counter_fu_40;
        end
    end else begin
        ap_sig_allocacmp_counter_16 = counter_fu_40;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_31 = 10'd0;
    end else begin
        ap_sig_allocacmp_i_31 = i_fu_44;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_basemul_add_blk_n = s_basemul_add_empty_n;
    end else begin
        s_basemul_add_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_basemul_add_read = 1'b1;
    end else begin
        s_basemul_add_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln989_reg_155 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sinvl_0_0_blk_n = sinvl_0_0_full_n;
    end else begin
        sinvl_0_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln989_reg_155 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sinvl_0_0_write = 1'b1;
    end else begin
        sinvl_0_0_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln989_reg_155 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sinvl_0_1_blk_n = sinvl_0_1_full_n;
    end else begin
        sinvl_0_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln989_reg_155 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sinvl_0_1_write = 1'b1;
    end else begin
        sinvl_0_1_write = 1'b0;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((s_basemul_add_empty_n == 1'b0) | ((sinvl_0_0_full_n == 1'b0) & (icmp_ln989_reg_155 == 1'd1)) | ((icmp_ln989_reg_155 == 1'd0) & (sinvl_0_1_full_n == 1'b0)));
end

always @ (*) begin
    ap_condition_116 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_213 = ((icmp_ln987_fu_92_p2 == 1'd0) & (ap_start_int == 1'b1) & (icmp_ln989_fu_104_p2 == 1'd1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = internal_ap_ready;

assign counter_19_fu_126_p3 = ((icmp_ln996_reg_164[0:0] == 1'b1) ? 32'd0 : counter_18_reg_159);

assign grp_fu_70_p2 = (ap_sig_allocacmp_counter_16 + 32'd1);

assign i_32_fu_98_p2 = (ap_sig_allocacmp_i_31 + 10'd1);

assign icmp_ln987_fu_92_p2 = ((ap_sig_allocacmp_i_31 == 10'd768) ? 1'b1 : 1'b0);

assign icmp_ln989_fu_104_p2 = (($signed(ap_sig_allocacmp_counter_16) < $signed(32'd1)) ? 1'b1 : 1'b0);

assign icmp_ln996_fu_110_p2 = ((grp_fu_70_p2 == 32'd2) ? 1'b1 : 1'b0);

assign sinvl_0_0_din = s_basemul_add_dout;

assign sinvl_0_1_din = s_basemul_add_dout;

assign start_out = real_start;

endmodule //mlkem_accelerator_split_short_64
