// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mlkem_accelerator_decompress (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        s_ct_0_dout,
        s_ct_0_num_data_valid,
        s_ct_0_fifo_cap,
        s_ct_0_empty_n,
        s_ct_0_read,
        s_d_b_din,
        s_d_b_num_data_valid,
        s_d_b_fifo_cap,
        s_d_b_full_n,
        s_d_b_write,
        s_d_v_din,
        s_d_v_num_data_valid,
        s_d_v_fifo_cap,
        s_d_v_full_n,
        s_d_v_write
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [7:0] s_ct_0_dout;
input  [12:0] s_ct_0_num_data_valid;
input  [12:0] s_ct_0_fifo_cap;
input   s_ct_0_empty_n;
output   s_ct_0_read;
output  [15:0] s_d_b_din;
input  [10:0] s_d_b_num_data_valid;
input  [10:0] s_d_b_fifo_cap;
input   s_d_b_full_n;
output   s_d_b_write;
output  [15:0] s_d_v_din;
input  [11:0] s_d_v_num_data_valid;
input  [11:0] s_d_v_fifo_cap;
input   s_d_v_full_n;
output   s_d_v_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg s_ct_0_read;
reg s_d_b_write;
reg s_d_v_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
wire    grp_decompress_Pipeline_VITIS_LOOP_357_2_VITIS_LOOP_358_3_fu_22_ap_start;
wire    grp_decompress_Pipeline_VITIS_LOOP_357_2_VITIS_LOOP_358_3_fu_22_ap_done;
wire    grp_decompress_Pipeline_VITIS_LOOP_357_2_VITIS_LOOP_358_3_fu_22_ap_idle;
wire    grp_decompress_Pipeline_VITIS_LOOP_357_2_VITIS_LOOP_358_3_fu_22_ap_ready;
wire    grp_decompress_Pipeline_VITIS_LOOP_357_2_VITIS_LOOP_358_3_fu_22_s_ct_0_read;
wire   [15:0] grp_decompress_Pipeline_VITIS_LOOP_357_2_VITIS_LOOP_358_3_fu_22_s_d_b_din;
wire    grp_decompress_Pipeline_VITIS_LOOP_357_2_VITIS_LOOP_358_3_fu_22_s_d_b_write;
wire    grp_decompress_Pipeline_VITIS_LOOP_384_5_fu_30_ap_start;
wire    grp_decompress_Pipeline_VITIS_LOOP_384_5_fu_30_ap_done;
wire    grp_decompress_Pipeline_VITIS_LOOP_384_5_fu_30_ap_idle;
wire    grp_decompress_Pipeline_VITIS_LOOP_384_5_fu_30_ap_ready;
wire    grp_decompress_Pipeline_VITIS_LOOP_384_5_fu_30_s_ct_0_read;
wire   [15:0] grp_decompress_Pipeline_VITIS_LOOP_384_5_fu_30_s_d_v_din;
wire    grp_decompress_Pipeline_VITIS_LOOP_384_5_fu_30_s_d_v_write;
reg    grp_decompress_Pipeline_VITIS_LOOP_357_2_VITIS_LOOP_358_3_fu_22_ap_start_reg;
reg    ap_block_state1_ignore_call13;
wire    ap_CS_fsm_state2;
reg    grp_decompress_Pipeline_VITIS_LOOP_384_5_fu_30_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg   [4:0] ap_NS_fsm;
reg    ap_block_state1;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 grp_decompress_Pipeline_VITIS_LOOP_357_2_VITIS_LOOP_358_3_fu_22_ap_start_reg = 1'b0;
#0 grp_decompress_Pipeline_VITIS_LOOP_384_5_fu_30_ap_start_reg = 1'b0;
end

mlkem_accelerator_decompress_Pipeline_VITIS_LOOP_357_2_VITIS_LOOP_358_3 grp_decompress_Pipeline_VITIS_LOOP_357_2_VITIS_LOOP_358_3_fu_22(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_decompress_Pipeline_VITIS_LOOP_357_2_VITIS_LOOP_358_3_fu_22_ap_start),
    .ap_done(grp_decompress_Pipeline_VITIS_LOOP_357_2_VITIS_LOOP_358_3_fu_22_ap_done),
    .ap_idle(grp_decompress_Pipeline_VITIS_LOOP_357_2_VITIS_LOOP_358_3_fu_22_ap_idle),
    .ap_ready(grp_decompress_Pipeline_VITIS_LOOP_357_2_VITIS_LOOP_358_3_fu_22_ap_ready),
    .s_ct_0_dout(s_ct_0_dout),
    .s_ct_0_num_data_valid(13'd0),
    .s_ct_0_fifo_cap(13'd0),
    .s_ct_0_empty_n(s_ct_0_empty_n),
    .s_ct_0_read(grp_decompress_Pipeline_VITIS_LOOP_357_2_VITIS_LOOP_358_3_fu_22_s_ct_0_read),
    .s_d_b_din(grp_decompress_Pipeline_VITIS_LOOP_357_2_VITIS_LOOP_358_3_fu_22_s_d_b_din),
    .s_d_b_num_data_valid(11'd0),
    .s_d_b_fifo_cap(11'd0),
    .s_d_b_full_n(s_d_b_full_n),
    .s_d_b_write(grp_decompress_Pipeline_VITIS_LOOP_357_2_VITIS_LOOP_358_3_fu_22_s_d_b_write)
);

mlkem_accelerator_decompress_Pipeline_VITIS_LOOP_384_5 grp_decompress_Pipeline_VITIS_LOOP_384_5_fu_30(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_decompress_Pipeline_VITIS_LOOP_384_5_fu_30_ap_start),
    .ap_done(grp_decompress_Pipeline_VITIS_LOOP_384_5_fu_30_ap_done),
    .ap_idle(grp_decompress_Pipeline_VITIS_LOOP_384_5_fu_30_ap_idle),
    .ap_ready(grp_decompress_Pipeline_VITIS_LOOP_384_5_fu_30_ap_ready),
    .s_ct_0_dout(s_ct_0_dout),
    .s_ct_0_num_data_valid(13'd0),
    .s_ct_0_fifo_cap(13'd0),
    .s_ct_0_empty_n(s_ct_0_empty_n),
    .s_ct_0_read(grp_decompress_Pipeline_VITIS_LOOP_384_5_fu_30_s_ct_0_read),
    .s_d_v_din(grp_decompress_Pipeline_VITIS_LOOP_384_5_fu_30_s_d_v_din),
    .s_d_v_num_data_valid(12'd0),
    .s_d_v_fifo_cap(12'd0),
    .s_d_v_full_n(s_d_v_full_n),
    .s_d_v_write(grp_decompress_Pipeline_VITIS_LOOP_384_5_fu_30_s_d_v_write)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_decompress_Pipeline_VITIS_LOOP_384_5_fu_30_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_decompress_Pipeline_VITIS_LOOP_357_2_VITIS_LOOP_358_3_fu_22_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state1_ignore_call13) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_decompress_Pipeline_VITIS_LOOP_357_2_VITIS_LOOP_358_3_fu_22_ap_start_reg <= 1'b1;
        end else if ((grp_decompress_Pipeline_VITIS_LOOP_357_2_VITIS_LOOP_358_3_fu_22_ap_ready == 1'b1)) begin
            grp_decompress_Pipeline_VITIS_LOOP_357_2_VITIS_LOOP_358_3_fu_22_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_decompress_Pipeline_VITIS_LOOP_384_5_fu_30_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_decompress_Pipeline_VITIS_LOOP_384_5_fu_30_ap_start_reg <= 1'b1;
        end else if ((grp_decompress_Pipeline_VITIS_LOOP_384_5_fu_30_ap_ready == 1'b1)) begin
            grp_decompress_Pipeline_VITIS_LOOP_384_5_fu_30_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_decompress_Pipeline_VITIS_LOOP_357_2_VITIS_LOOP_358_3_fu_22_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_decompress_Pipeline_VITIS_LOOP_384_5_fu_30_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_decompress_Pipeline_VITIS_LOOP_384_5_fu_30_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_decompress_Pipeline_VITIS_LOOP_384_5_fu_30_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        s_ct_0_read = grp_decompress_Pipeline_VITIS_LOOP_384_5_fu_30_s_ct_0_read;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        s_ct_0_read = grp_decompress_Pipeline_VITIS_LOOP_357_2_VITIS_LOOP_358_3_fu_22_s_ct_0_read;
    end else begin
        s_ct_0_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        s_d_b_write = grp_decompress_Pipeline_VITIS_LOOP_357_2_VITIS_LOOP_358_3_fu_22_s_d_b_write;
    end else begin
        s_d_b_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        s_d_v_write = grp_decompress_Pipeline_VITIS_LOOP_384_5_fu_30_s_d_v_write;
    end else begin
        s_d_v_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_decompress_Pipeline_VITIS_LOOP_357_2_VITIS_LOOP_358_3_fu_22_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_decompress_Pipeline_VITIS_LOOP_384_5_fu_30_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call13 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign grp_decompress_Pipeline_VITIS_LOOP_357_2_VITIS_LOOP_358_3_fu_22_ap_start = grp_decompress_Pipeline_VITIS_LOOP_357_2_VITIS_LOOP_358_3_fu_22_ap_start_reg;

assign grp_decompress_Pipeline_VITIS_LOOP_384_5_fu_30_ap_start = grp_decompress_Pipeline_VITIS_LOOP_384_5_fu_30_ap_start_reg;

assign s_d_b_din = grp_decompress_Pipeline_VITIS_LOOP_357_2_VITIS_LOOP_358_3_fu_22_s_d_b_din;

assign s_d_v_din = grp_decompress_Pipeline_VITIS_LOOP_384_5_fu_30_s_d_v_din;

assign start_out = real_start;

endmodule //mlkem_accelerator_decompress
