// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mlkem_accelerator_merge_short_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        s_d_nttl_0_1_dout,
        s_d_nttl_0_1_num_data_valid,
        s_d_nttl_0_1_fifo_cap,
        s_d_nttl_0_1_empty_n,
        s_d_nttl_0_1_read,
        s_d_nttl_0_0_dout,
        s_d_nttl_0_0_num_data_valid,
        s_d_nttl_0_0_fifo_cap,
        s_d_nttl_0_0_empty_n,
        s_d_nttl_0_0_read,
        s_d_ntt_out_din,
        s_d_ntt_out_num_data_valid,
        s_d_ntt_out_fifo_cap,
        s_d_ntt_out_full_n,
        s_d_ntt_out_write,
        start_out,
        start_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] s_d_nttl_0_1_dout;
input  [7:0] s_d_nttl_0_1_num_data_valid;
input  [7:0] s_d_nttl_0_1_fifo_cap;
input   s_d_nttl_0_1_empty_n;
output   s_d_nttl_0_1_read;
input  [15:0] s_d_nttl_0_0_dout;
input  [7:0] s_d_nttl_0_0_num_data_valid;
input  [7:0] s_d_nttl_0_0_fifo_cap;
input   s_d_nttl_0_0_empty_n;
output   s_d_nttl_0_0_read;
output  [15:0] s_d_ntt_out_din;
input  [9:0] s_d_ntt_out_num_data_valid;
input  [9:0] s_d_ntt_out_fifo_cap;
input   s_d_ntt_out_full_n;
output   s_d_ntt_out_write;
output   start_out;
output   start_write;

reg ap_idle;
reg s_d_nttl_0_1_read;
reg s_d_nttl_0_0_read;
reg s_d_ntt_out_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] icmp_ln1043_reg_159;
reg   [0:0] icmp_ln1045_reg_163;
reg    ap_predicate_op38_read_state2;
reg    ap_predicate_op42_read_state2;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln1043_fu_99_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    s_d_nttl_0_0_blk_n;
wire    ap_block_pp0_stage0;
reg    s_d_nttl_0_1_blk_n;
reg    s_d_ntt_out_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln1045_fu_111_p2;
wire   [31:0] grp_fu_77_p2;
reg   [31:0] counter_62_reg_167;
wire   [0:0] icmp_ln1052_fu_117_p2;
reg   [0:0] icmp_ln1052_reg_172;
wire   [15:0] ap_phi_reg_pp0_iter0_t_32_reg_67;
reg   [15:0] ap_phi_reg_pp0_iter1_t_32_reg_67;
reg   [15:0] ap_phi_reg_pp0_iter2_t_32_reg_67;
reg   [31:0] counter_fu_40;
wire   [31:0] counter_63_fu_133_p3;
reg   [31:0] ap_sig_allocacmp_counter_60;
wire    ap_loop_init;
reg   [9:0] i_fu_44;
wire   [9:0] i_116_fu_105_p2;
reg   [9:0] ap_sig_allocacmp_i_115;
reg    ap_block_pp0_stage0_01001;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_150;
reg    ap_condition_247;
reg    ap_condition_252;
reg    ap_condition_138;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 counter_fu_40 = 32'd0;
#0 i_fu_44 = 10'd0;
end

mlkem_accelerator_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_150)) begin
        if (((icmp_ln1045_reg_163 == 1'd0) & (icmp_ln1043_reg_159 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_t_32_reg_67 <= s_d_nttl_0_1_dout;
        end else if (((icmp_ln1045_reg_163 == 1'd1) & (icmp_ln1043_reg_159 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_t_32_reg_67 <= s_d_nttl_0_0_dout;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_t_32_reg_67 <= ap_phi_reg_pp0_iter1_t_32_reg_67;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((1'b1 == ap_condition_252)) begin
            counter_fu_40 <= grp_fu_77_p2;
        end else if (((ap_start_int == 1'b1) & (ap_loop_init == 1'b1))) begin
            counter_fu_40 <= 32'd0;
        end else if ((1'b1 == ap_condition_247)) begin
            counter_fu_40 <= counter_63_fu_133_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_138)) begin
        if ((icmp_ln1043_fu_99_p2 == 1'd0)) begin
            i_fu_44 <= i_116_fu_105_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_44 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln1043_reg_159 <= icmp_ln1043_fu_99_p2;
        icmp_ln1045_reg_163 <= icmp_ln1045_fu_111_p2;
        icmp_ln1052_reg_172 <= icmp_ln1052_fu_117_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_t_32_reg_67 <= ap_phi_reg_pp0_iter0_t_32_reg_67;
        counter_62_reg_167 <= grp_fu_77_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1043_fu_99_p2 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_start_int == 1'b1) & (ap_loop_init == 1'b1))) begin
            ap_sig_allocacmp_counter_60 = 32'd0;
        end else if ((1'b1 == ap_condition_247)) begin
            ap_sig_allocacmp_counter_60 = counter_63_fu_133_p3;
        end else begin
            ap_sig_allocacmp_counter_60 = counter_fu_40;
        end
    end else begin
        ap_sig_allocacmp_counter_60 = counter_fu_40;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_115 = 10'd0;
    end else begin
        ap_sig_allocacmp_i_115 = i_fu_44;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        s_d_ntt_out_blk_n = s_d_ntt_out_full_n;
    end else begin
        s_d_ntt_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        s_d_ntt_out_write = 1'b1;
    end else begin
        s_d_ntt_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op42_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_d_nttl_0_0_blk_n = s_d_nttl_0_0_empty_n;
    end else begin
        s_d_nttl_0_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op42_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_d_nttl_0_0_read = 1'b1;
    end else begin
        s_d_nttl_0_0_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op38_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_d_nttl_0_1_blk_n = s_d_nttl_0_1_empty_n;
    end else begin
        s_d_nttl_0_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op38_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_d_nttl_0_1_read = 1'b1;
    end else begin
        s_d_nttl_0_1_read = 1'b0;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (((ap_predicate_op42_read_state2 == 1'b1) & (s_d_nttl_0_0_empty_n == 1'b0)) | ((ap_predicate_op38_read_state2 == 1'b1) & (s_d_nttl_0_1_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (s_d_ntt_out_full_n == 1'b0);
end

always @ (*) begin
    ap_condition_138 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_150 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_247 = ((icmp_ln1045_reg_163 == 1'd0) & (icmp_ln1043_reg_159 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_252 = ((ap_start_int == 1'b1) & (icmp_ln1045_fu_111_p2 == 1'd1) & (icmp_ln1043_fu_99_p2 == 1'd0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_t_32_reg_67 = 'bx;

always @ (*) begin
    ap_predicate_op38_read_state2 = ((icmp_ln1045_reg_163 == 1'd0) & (icmp_ln1043_reg_159 == 1'd0));
end

always @ (*) begin
    ap_predicate_op42_read_state2 = ((icmp_ln1045_reg_163 == 1'd1) & (icmp_ln1043_reg_159 == 1'd0));
end

assign ap_ready = internal_ap_ready;

assign counter_63_fu_133_p3 = ((icmp_ln1052_reg_172[0:0] == 1'b1) ? 32'd0 : counter_62_reg_167);

assign grp_fu_77_p2 = (ap_sig_allocacmp_counter_60 + 32'd1);

assign i_116_fu_105_p2 = (ap_sig_allocacmp_i_115 + 10'd1);

assign icmp_ln1043_fu_99_p2 = ((ap_sig_allocacmp_i_115 == 10'd512) ? 1'b1 : 1'b0);

assign icmp_ln1045_fu_111_p2 = (($signed(ap_sig_allocacmp_counter_60) < $signed(32'd1)) ? 1'b1 : 1'b0);

assign icmp_ln1052_fu_117_p2 = ((grp_fu_77_p2 == 32'd2) ? 1'b1 : 1'b0);

assign s_d_ntt_out_din = ap_phi_reg_pp0_iter2_t_32_reg_67;

assign start_out = real_start;

endmodule //mlkem_accelerator_merge_short_s
