// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mlkem_accelerator_absorb_permute (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        p_read16,
        p_read17,
        p_read18,
        p_read19,
        p_read20,
        p_read21,
        p_read22,
        p_read23,
        p_read24,
        k_kem_enc_s_key_dout,
        k_kem_enc_s_key_num_data_valid,
        k_kem_enc_s_key_fifo_cap,
        k_kem_enc_s_key_empty_n,
        k_kem_enc_s_key_read,
        act,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] p_read;
input  [63:0] p_read1;
input  [63:0] p_read2;
input  [63:0] p_read3;
input  [63:0] p_read4;
input  [63:0] p_read5;
input  [63:0] p_read6;
input  [63:0] p_read7;
input  [63:0] p_read8;
input  [63:0] p_read9;
input  [63:0] p_read10;
input  [63:0] p_read11;
input  [63:0] p_read12;
input  [63:0] p_read13;
input  [63:0] p_read14;
input  [63:0] p_read15;
input  [63:0] p_read16;
input  [63:0] p_read17;
input  [63:0] p_read18;
input  [63:0] p_read19;
input  [63:0] p_read20;
input  [63:0] p_read21;
input  [63:0] p_read22;
input  [63:0] p_read23;
input  [63:0] p_read24;
input  [263:0] k_kem_enc_s_key_dout;
input  [2:0] k_kem_enc_s_key_num_data_valid;
input  [2:0] k_kem_enc_s_key_fifo_cap;
input   k_kem_enc_s_key_empty_n;
output   k_kem_enc_s_key_read;
input  [0:0] act;
output  [63:0] ap_return_0;
output  [63:0] ap_return_1;
output  [63:0] ap_return_2;
output  [63:0] ap_return_3;
output  [63:0] ap_return_4;
output  [63:0] ap_return_5;
output  [63:0] ap_return_6;
output  [63:0] ap_return_7;
output  [63:0] ap_return_8;
output  [63:0] ap_return_9;
output  [63:0] ap_return_10;
output  [63:0] ap_return_11;
output  [63:0] ap_return_12;
output  [63:0] ap_return_13;
output  [63:0] ap_return_14;
output  [63:0] ap_return_15;
output  [63:0] ap_return_16;
output  [63:0] ap_return_17;
output  [63:0] ap_return_18;
output  [63:0] ap_return_19;
output  [63:0] ap_return_20;
output  [63:0] ap_return_21;
output  [63:0] ap_return_22;
output  [63:0] ap_return_23;
output  [63:0] ap_return_24;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg k_kem_enc_s_key_read;
reg[63:0] ap_return_0;
reg[63:0] ap_return_1;
reg[63:0] ap_return_2;
reg[63:0] ap_return_3;
reg[63:0] ap_return_4;
reg[63:0] ap_return_5;
reg[63:0] ap_return_6;
reg[63:0] ap_return_7;
reg[63:0] ap_return_8;
reg[63:0] ap_return_9;
reg[63:0] ap_return_10;
reg[63:0] ap_return_11;
reg[63:0] ap_return_12;
reg[63:0] ap_return_13;
reg[63:0] ap_return_14;
reg[63:0] ap_return_15;
reg[63:0] ap_return_16;
reg[63:0] ap_return_17;
reg[63:0] ap_return_18;
reg[63:0] ap_return_19;
reg[63:0] ap_return_20;
reg[63:0] ap_return_21;
reg[63:0] ap_return_22;
reg[63:0] ap_return_23;
reg[63:0] ap_return_24;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    absorb_ret_absorb_fu_230_k_kem_dec_s_key_blk_n;
reg    k_kem_enc_s_key_blk_n;
reg   [63:0] s_0_assign_3_reg_444;
reg   [63:0] s_1_assign_3_reg_449;
reg   [63:0] s_2_assign_3_reg_454;
reg   [63:0] s_3_assign_3_reg_459;
reg   [63:0] s_4_assign_3_reg_464;
reg   [63:0] s_5_assign_3_reg_469;
reg   [63:0] s_6_assign_3_reg_474;
reg   [63:0] s_7_assign_3_reg_479;
reg   [63:0] s_8_assign_3_reg_484;
reg   [63:0] s_9_assign_3_reg_489;
reg   [63:0] s_10_assign_3_reg_494;
reg   [63:0] s_11_assign_3_reg_499;
reg   [63:0] s_12_assign_3_reg_504;
reg   [63:0] s_1315_assign_3_reg_509;
reg   [63:0] s_14_assign_3_reg_514;
reg   [63:0] s_15_assign_3_reg_519;
reg   [63:0] s_16_assign_3_reg_524;
reg   [63:0] s_17_assign_3_reg_529;
reg   [63:0] s_18_assign_3_reg_534;
reg   [63:0] s_19_assign_3_reg_539;
reg   [63:0] s_20_assign_3_reg_544;
reg   [63:0] s_21_assign_3_reg_549;
reg   [63:0] s_22_assign_3_reg_554;
reg   [63:0] s_23_assign_3_reg_559;
reg   [63:0] s_2427_assign_3_reg_564;
reg    absorb_ret_absorb_fu_230_ap_start;
wire    absorb_ret_absorb_fu_230_ap_done;
wire    absorb_ret_absorb_fu_230_ap_idle;
wire    absorb_ret_absorb_fu_230_ap_ready;
wire    absorb_ret_absorb_fu_230_k_kem_dec_s_key_read;
wire   [63:0] absorb_ret_absorb_fu_230_ap_return_0;
wire   [63:0] absorb_ret_absorb_fu_230_ap_return_1;
wire   [63:0] absorb_ret_absorb_fu_230_ap_return_2;
wire   [63:0] absorb_ret_absorb_fu_230_ap_return_3;
wire   [63:0] absorb_ret_absorb_fu_230_ap_return_4;
wire   [63:0] absorb_ret_absorb_fu_230_ap_return_5;
wire   [63:0] absorb_ret_absorb_fu_230_ap_return_6;
wire   [63:0] absorb_ret_absorb_fu_230_ap_return_7;
wire   [63:0] absorb_ret_absorb_fu_230_ap_return_8;
wire   [63:0] absorb_ret_absorb_fu_230_ap_return_9;
wire   [63:0] absorb_ret_absorb_fu_230_ap_return_10;
wire   [63:0] absorb_ret_absorb_fu_230_ap_return_11;
wire   [63:0] absorb_ret_absorb_fu_230_ap_return_12;
wire   [63:0] absorb_ret_absorb_fu_230_ap_return_13;
wire   [63:0] absorb_ret_absorb_fu_230_ap_return_14;
wire   [63:0] absorb_ret_absorb_fu_230_ap_return_15;
wire   [63:0] absorb_ret_absorb_fu_230_ap_return_16;
wire   [63:0] absorb_ret_absorb_fu_230_ap_return_17;
wire   [63:0] absorb_ret_absorb_fu_230_ap_return_18;
wire   [63:0] absorb_ret_absorb_fu_230_ap_return_19;
wire   [63:0] absorb_ret_absorb_fu_230_ap_return_20;
wire   [63:0] absorb_ret_absorb_fu_230_ap_return_21;
wire   [63:0] absorb_ret_absorb_fu_230_ap_return_22;
wire   [63:0] absorb_ret_absorb_fu_230_ap_return_23;
wire   [63:0] absorb_ret_absorb_fu_230_ap_return_24;
wire    grp_KeccakF1600_StatePermute_fu_288_ap_start;
wire    grp_KeccakF1600_StatePermute_fu_288_ap_done;
wire    grp_KeccakF1600_StatePermute_fu_288_ap_idle;
wire    grp_KeccakF1600_StatePermute_fu_288_ap_ready;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_288_ap_return_0;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_288_ap_return_1;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_288_ap_return_2;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_288_ap_return_3;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_288_ap_return_4;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_288_ap_return_5;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_288_ap_return_6;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_288_ap_return_7;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_288_ap_return_8;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_288_ap_return_9;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_288_ap_return_10;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_288_ap_return_11;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_288_ap_return_12;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_288_ap_return_13;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_288_ap_return_14;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_288_ap_return_15;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_288_ap_return_16;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_288_ap_return_17;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_288_ap_return_18;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_288_ap_return_19;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_288_ap_return_20;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_288_ap_return_21;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_288_ap_return_22;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_288_ap_return_23;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_288_ap_return_24;
reg    grp_KeccakF1600_StatePermute_fu_288_ap_start_reg;
reg    ap_block_state1_ignore_call53;
wire    ap_CS_fsm_state2;
reg    ap_block_state1;
reg   [63:0] ap_return_0_preg;
reg   [63:0] ap_return_1_preg;
reg   [63:0] ap_return_2_preg;
reg   [63:0] ap_return_3_preg;
reg   [63:0] ap_return_4_preg;
reg   [63:0] ap_return_5_preg;
reg   [63:0] ap_return_6_preg;
reg   [63:0] ap_return_7_preg;
reg   [63:0] ap_return_8_preg;
reg   [63:0] ap_return_9_preg;
reg   [63:0] ap_return_10_preg;
reg   [63:0] ap_return_11_preg;
reg   [63:0] ap_return_12_preg;
reg   [63:0] ap_return_13_preg;
reg   [63:0] ap_return_14_preg;
reg   [63:0] ap_return_15_preg;
reg   [63:0] ap_return_16_preg;
reg   [63:0] ap_return_17_preg;
reg   [63:0] ap_return_18_preg;
reg   [63:0] ap_return_19_preg;
reg   [63:0] ap_return_20_preg;
reg   [63:0] ap_return_21_preg;
reg   [63:0] ap_return_22_preg;
reg   [63:0] ap_return_23_preg;
reg   [63:0] ap_return_24_preg;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 grp_KeccakF1600_StatePermute_fu_288_ap_start_reg = 1'b0;
#0 ap_return_0_preg = 64'd0;
#0 ap_return_1_preg = 64'd0;
#0 ap_return_2_preg = 64'd0;
#0 ap_return_3_preg = 64'd0;
#0 ap_return_4_preg = 64'd0;
#0 ap_return_5_preg = 64'd0;
#0 ap_return_6_preg = 64'd0;
#0 ap_return_7_preg = 64'd0;
#0 ap_return_8_preg = 64'd0;
#0 ap_return_9_preg = 64'd0;
#0 ap_return_10_preg = 64'd0;
#0 ap_return_11_preg = 64'd0;
#0 ap_return_12_preg = 64'd0;
#0 ap_return_13_preg = 64'd0;
#0 ap_return_14_preg = 64'd0;
#0 ap_return_15_preg = 64'd0;
#0 ap_return_16_preg = 64'd0;
#0 ap_return_17_preg = 64'd0;
#0 ap_return_18_preg = 64'd0;
#0 ap_return_19_preg = 64'd0;
#0 ap_return_20_preg = 64'd0;
#0 ap_return_21_preg = 64'd0;
#0 ap_return_22_preg = 64'd0;
#0 ap_return_23_preg = 64'd0;
#0 ap_return_24_preg = 64'd0;
end

mlkem_accelerator_absorb absorb_ret_absorb_fu_230(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(absorb_ret_absorb_fu_230_ap_start),
    .ap_done(absorb_ret_absorb_fu_230_ap_done),
    .ap_idle(absorb_ret_absorb_fu_230_ap_idle),
    .ap_ready(absorb_ret_absorb_fu_230_ap_ready),
    .p_read(p_read),
    .p_read1(p_read1),
    .p_read2(p_read2),
    .p_read3(p_read3),
    .p_read4(p_read4),
    .p_read5(p_read5),
    .p_read6(p_read6),
    .p_read7(p_read7),
    .p_read8(p_read8),
    .p_read9(p_read9),
    .p_read10(p_read10),
    .p_read11(p_read11),
    .p_read12(p_read12),
    .p_read13(p_read13),
    .p_read14(p_read14),
    .p_read15(p_read15),
    .p_read16(p_read16),
    .p_read17(p_read17),
    .p_read18(p_read18),
    .p_read19(p_read19),
    .p_read20(p_read20),
    .p_read21(p_read21),
    .p_read22(p_read22),
    .p_read23(p_read23),
    .p_read24(p_read24),
    .k_kem_dec_s_key_dout(k_kem_enc_s_key_dout),
    .k_kem_dec_s_key_num_data_valid(3'd0),
    .k_kem_dec_s_key_fifo_cap(3'd0),
    .k_kem_dec_s_key_empty_n(k_kem_enc_s_key_empty_n),
    .k_kem_dec_s_key_read(absorb_ret_absorb_fu_230_k_kem_dec_s_key_read),
    .act(act),
    .ap_return_0(absorb_ret_absorb_fu_230_ap_return_0),
    .ap_return_1(absorb_ret_absorb_fu_230_ap_return_1),
    .ap_return_2(absorb_ret_absorb_fu_230_ap_return_2),
    .ap_return_3(absorb_ret_absorb_fu_230_ap_return_3),
    .ap_return_4(absorb_ret_absorb_fu_230_ap_return_4),
    .ap_return_5(absorb_ret_absorb_fu_230_ap_return_5),
    .ap_return_6(absorb_ret_absorb_fu_230_ap_return_6),
    .ap_return_7(absorb_ret_absorb_fu_230_ap_return_7),
    .ap_return_8(absorb_ret_absorb_fu_230_ap_return_8),
    .ap_return_9(absorb_ret_absorb_fu_230_ap_return_9),
    .ap_return_10(absorb_ret_absorb_fu_230_ap_return_10),
    .ap_return_11(absorb_ret_absorb_fu_230_ap_return_11),
    .ap_return_12(absorb_ret_absorb_fu_230_ap_return_12),
    .ap_return_13(absorb_ret_absorb_fu_230_ap_return_13),
    .ap_return_14(absorb_ret_absorb_fu_230_ap_return_14),
    .ap_return_15(absorb_ret_absorb_fu_230_ap_return_15),
    .ap_return_16(absorb_ret_absorb_fu_230_ap_return_16),
    .ap_return_17(absorb_ret_absorb_fu_230_ap_return_17),
    .ap_return_18(absorb_ret_absorb_fu_230_ap_return_18),
    .ap_return_19(absorb_ret_absorb_fu_230_ap_return_19),
    .ap_return_20(absorb_ret_absorb_fu_230_ap_return_20),
    .ap_return_21(absorb_ret_absorb_fu_230_ap_return_21),
    .ap_return_22(absorb_ret_absorb_fu_230_ap_return_22),
    .ap_return_23(absorb_ret_absorb_fu_230_ap_return_23),
    .ap_return_24(absorb_ret_absorb_fu_230_ap_return_24),
    .k_kem_dec_s_key_blk_n(absorb_ret_absorb_fu_230_k_kem_dec_s_key_blk_n)
);

mlkem_accelerator_KeccakF1600_StatePermute grp_KeccakF1600_StatePermute_fu_288(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_KeccakF1600_StatePermute_fu_288_ap_start),
    .ap_done(grp_KeccakF1600_StatePermute_fu_288_ap_done),
    .ap_idle(grp_KeccakF1600_StatePermute_fu_288_ap_idle),
    .ap_ready(grp_KeccakF1600_StatePermute_fu_288_ap_ready),
    .state_read(s_0_assign_3_reg_444),
    .state_read_49(s_1_assign_3_reg_449),
    .state_read_50(s_2_assign_3_reg_454),
    .state_read_51(s_3_assign_3_reg_459),
    .state_read_52(s_4_assign_3_reg_464),
    .state_read_53(s_5_assign_3_reg_469),
    .state_read_54(s_6_assign_3_reg_474),
    .state_read_55(s_7_assign_3_reg_479),
    .state_read_56(s_8_assign_3_reg_484),
    .state_read_57(s_9_assign_3_reg_489),
    .state_read_58(s_10_assign_3_reg_494),
    .state_read_59(s_11_assign_3_reg_499),
    .state_read_60(s_12_assign_3_reg_504),
    .state_read_61(s_1315_assign_3_reg_509),
    .state_read_62(s_14_assign_3_reg_514),
    .state_read_63(s_15_assign_3_reg_519),
    .state_read_64(s_16_assign_3_reg_524),
    .state_read_65(s_17_assign_3_reg_529),
    .state_read_66(s_18_assign_3_reg_534),
    .state_read_67(s_19_assign_3_reg_539),
    .state_read_68(s_20_assign_3_reg_544),
    .state_read_69(s_21_assign_3_reg_549),
    .state_read_70(s_22_assign_3_reg_554),
    .state_read_71(s_23_assign_3_reg_559),
    .state_read_72(s_2427_assign_3_reg_564),
    .ap_return_0(grp_KeccakF1600_StatePermute_fu_288_ap_return_0),
    .ap_return_1(grp_KeccakF1600_StatePermute_fu_288_ap_return_1),
    .ap_return_2(grp_KeccakF1600_StatePermute_fu_288_ap_return_2),
    .ap_return_3(grp_KeccakF1600_StatePermute_fu_288_ap_return_3),
    .ap_return_4(grp_KeccakF1600_StatePermute_fu_288_ap_return_4),
    .ap_return_5(grp_KeccakF1600_StatePermute_fu_288_ap_return_5),
    .ap_return_6(grp_KeccakF1600_StatePermute_fu_288_ap_return_6),
    .ap_return_7(grp_KeccakF1600_StatePermute_fu_288_ap_return_7),
    .ap_return_8(grp_KeccakF1600_StatePermute_fu_288_ap_return_8),
    .ap_return_9(grp_KeccakF1600_StatePermute_fu_288_ap_return_9),
    .ap_return_10(grp_KeccakF1600_StatePermute_fu_288_ap_return_10),
    .ap_return_11(grp_KeccakF1600_StatePermute_fu_288_ap_return_11),
    .ap_return_12(grp_KeccakF1600_StatePermute_fu_288_ap_return_12),
    .ap_return_13(grp_KeccakF1600_StatePermute_fu_288_ap_return_13),
    .ap_return_14(grp_KeccakF1600_StatePermute_fu_288_ap_return_14),
    .ap_return_15(grp_KeccakF1600_StatePermute_fu_288_ap_return_15),
    .ap_return_16(grp_KeccakF1600_StatePermute_fu_288_ap_return_16),
    .ap_return_17(grp_KeccakF1600_StatePermute_fu_288_ap_return_17),
    .ap_return_18(grp_KeccakF1600_StatePermute_fu_288_ap_return_18),
    .ap_return_19(grp_KeccakF1600_StatePermute_fu_288_ap_return_19),
    .ap_return_20(grp_KeccakF1600_StatePermute_fu_288_ap_return_20),
    .ap_return_21(grp_KeccakF1600_StatePermute_fu_288_ap_return_21),
    .ap_return_22(grp_KeccakF1600_StatePermute_fu_288_ap_return_22),
    .ap_return_23(grp_KeccakF1600_StatePermute_fu_288_ap_return_23),
    .ap_return_24(grp_KeccakF1600_StatePermute_fu_288_ap_return_24)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 64'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
            ap_return_0_preg <= grp_KeccakF1600_StatePermute_fu_288_ap_return_0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_10_preg <= 64'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
            ap_return_10_preg <= grp_KeccakF1600_StatePermute_fu_288_ap_return_10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_11_preg <= 64'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
            ap_return_11_preg <= grp_KeccakF1600_StatePermute_fu_288_ap_return_11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_12_preg <= 64'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
            ap_return_12_preg <= grp_KeccakF1600_StatePermute_fu_288_ap_return_12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_13_preg <= 64'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
            ap_return_13_preg <= grp_KeccakF1600_StatePermute_fu_288_ap_return_13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_14_preg <= 64'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
            ap_return_14_preg <= grp_KeccakF1600_StatePermute_fu_288_ap_return_14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_15_preg <= 64'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
            ap_return_15_preg <= grp_KeccakF1600_StatePermute_fu_288_ap_return_15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_16_preg <= 64'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
            ap_return_16_preg <= grp_KeccakF1600_StatePermute_fu_288_ap_return_16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_17_preg <= 64'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
            ap_return_17_preg <= grp_KeccakF1600_StatePermute_fu_288_ap_return_17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_18_preg <= 64'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
            ap_return_18_preg <= grp_KeccakF1600_StatePermute_fu_288_ap_return_18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_19_preg <= 64'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
            ap_return_19_preg <= grp_KeccakF1600_StatePermute_fu_288_ap_return_19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 64'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
            ap_return_1_preg <= grp_KeccakF1600_StatePermute_fu_288_ap_return_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_20_preg <= 64'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
            ap_return_20_preg <= grp_KeccakF1600_StatePermute_fu_288_ap_return_20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_21_preg <= 64'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
            ap_return_21_preg <= grp_KeccakF1600_StatePermute_fu_288_ap_return_21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_22_preg <= 64'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
            ap_return_22_preg <= grp_KeccakF1600_StatePermute_fu_288_ap_return_22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_23_preg <= 64'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
            ap_return_23_preg <= grp_KeccakF1600_StatePermute_fu_288_ap_return_23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_24_preg <= 64'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
            ap_return_24_preg <= grp_KeccakF1600_StatePermute_fu_288_ap_return_24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_2_preg <= 64'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
            ap_return_2_preg <= grp_KeccakF1600_StatePermute_fu_288_ap_return_2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_3_preg <= 64'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
            ap_return_3_preg <= grp_KeccakF1600_StatePermute_fu_288_ap_return_3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_4_preg <= 64'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
            ap_return_4_preg <= grp_KeccakF1600_StatePermute_fu_288_ap_return_4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_5_preg <= 64'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
            ap_return_5_preg <= grp_KeccakF1600_StatePermute_fu_288_ap_return_5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_6_preg <= 64'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
            ap_return_6_preg <= grp_KeccakF1600_StatePermute_fu_288_ap_return_6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_7_preg <= 64'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
            ap_return_7_preg <= grp_KeccakF1600_StatePermute_fu_288_ap_return_7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_8_preg <= 64'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
            ap_return_8_preg <= grp_KeccakF1600_StatePermute_fu_288_ap_return_8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_9_preg <= 64'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
            ap_return_9_preg <= grp_KeccakF1600_StatePermute_fu_288_ap_return_9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_KeccakF1600_StatePermute_fu_288_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state1_ignore_call53) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_KeccakF1600_StatePermute_fu_288_ap_start_reg <= 1'b1;
        end else if ((grp_KeccakF1600_StatePermute_fu_288_ap_ready == 1'b1)) begin
            grp_KeccakF1600_StatePermute_fu_288_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        s_0_assign_3_reg_444 <= absorb_ret_absorb_fu_230_ap_return_0;
        s_10_assign_3_reg_494 <= absorb_ret_absorb_fu_230_ap_return_10;
        s_11_assign_3_reg_499 <= absorb_ret_absorb_fu_230_ap_return_11;
        s_12_assign_3_reg_504 <= absorb_ret_absorb_fu_230_ap_return_12;
        s_1315_assign_3_reg_509 <= absorb_ret_absorb_fu_230_ap_return_13;
        s_14_assign_3_reg_514 <= absorb_ret_absorb_fu_230_ap_return_14;
        s_15_assign_3_reg_519 <= absorb_ret_absorb_fu_230_ap_return_15;
        s_16_assign_3_reg_524 <= absorb_ret_absorb_fu_230_ap_return_16;
        s_17_assign_3_reg_529 <= absorb_ret_absorb_fu_230_ap_return_17;
        s_18_assign_3_reg_534 <= absorb_ret_absorb_fu_230_ap_return_18;
        s_19_assign_3_reg_539 <= absorb_ret_absorb_fu_230_ap_return_19;
        s_1_assign_3_reg_449 <= absorb_ret_absorb_fu_230_ap_return_1;
        s_20_assign_3_reg_544 <= absorb_ret_absorb_fu_230_ap_return_20;
        s_21_assign_3_reg_549 <= absorb_ret_absorb_fu_230_ap_return_21;
        s_22_assign_3_reg_554 <= absorb_ret_absorb_fu_230_ap_return_22;
        s_23_assign_3_reg_559 <= absorb_ret_absorb_fu_230_ap_return_23;
        s_2427_assign_3_reg_564 <= absorb_ret_absorb_fu_230_ap_return_24;
        s_2_assign_3_reg_454 <= absorb_ret_absorb_fu_230_ap_return_2;
        s_3_assign_3_reg_459 <= absorb_ret_absorb_fu_230_ap_return_3;
        s_4_assign_3_reg_464 <= absorb_ret_absorb_fu_230_ap_return_4;
        s_5_assign_3_reg_469 <= absorb_ret_absorb_fu_230_ap_return_5;
        s_6_assign_3_reg_474 <= absorb_ret_absorb_fu_230_ap_return_6;
        s_7_assign_3_reg_479 <= absorb_ret_absorb_fu_230_ap_return_7;
        s_8_assign_3_reg_484 <= absorb_ret_absorb_fu_230_ap_return_8;
        s_9_assign_3_reg_489 <= absorb_ret_absorb_fu_230_ap_return_9;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        absorb_ret_absorb_fu_230_ap_start = 1'b1;
    end else begin
        absorb_ret_absorb_fu_230_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
        ap_return_0 = grp_KeccakF1600_StatePermute_fu_288_ap_return_0;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
        ap_return_1 = grp_KeccakF1600_StatePermute_fu_288_ap_return_1;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
        ap_return_10 = grp_KeccakF1600_StatePermute_fu_288_ap_return_10;
    end else begin
        ap_return_10 = ap_return_10_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
        ap_return_11 = grp_KeccakF1600_StatePermute_fu_288_ap_return_11;
    end else begin
        ap_return_11 = ap_return_11_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
        ap_return_12 = grp_KeccakF1600_StatePermute_fu_288_ap_return_12;
    end else begin
        ap_return_12 = ap_return_12_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
        ap_return_13 = grp_KeccakF1600_StatePermute_fu_288_ap_return_13;
    end else begin
        ap_return_13 = ap_return_13_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
        ap_return_14 = grp_KeccakF1600_StatePermute_fu_288_ap_return_14;
    end else begin
        ap_return_14 = ap_return_14_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
        ap_return_15 = grp_KeccakF1600_StatePermute_fu_288_ap_return_15;
    end else begin
        ap_return_15 = ap_return_15_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
        ap_return_16 = grp_KeccakF1600_StatePermute_fu_288_ap_return_16;
    end else begin
        ap_return_16 = ap_return_16_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
        ap_return_17 = grp_KeccakF1600_StatePermute_fu_288_ap_return_17;
    end else begin
        ap_return_17 = ap_return_17_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
        ap_return_18 = grp_KeccakF1600_StatePermute_fu_288_ap_return_18;
    end else begin
        ap_return_18 = ap_return_18_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
        ap_return_19 = grp_KeccakF1600_StatePermute_fu_288_ap_return_19;
    end else begin
        ap_return_19 = ap_return_19_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
        ap_return_2 = grp_KeccakF1600_StatePermute_fu_288_ap_return_2;
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
        ap_return_20 = grp_KeccakF1600_StatePermute_fu_288_ap_return_20;
    end else begin
        ap_return_20 = ap_return_20_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
        ap_return_21 = grp_KeccakF1600_StatePermute_fu_288_ap_return_21;
    end else begin
        ap_return_21 = ap_return_21_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
        ap_return_22 = grp_KeccakF1600_StatePermute_fu_288_ap_return_22;
    end else begin
        ap_return_22 = ap_return_22_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
        ap_return_23 = grp_KeccakF1600_StatePermute_fu_288_ap_return_23;
    end else begin
        ap_return_23 = ap_return_23_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
        ap_return_24 = grp_KeccakF1600_StatePermute_fu_288_ap_return_24;
    end else begin
        ap_return_24 = ap_return_24_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
        ap_return_3 = grp_KeccakF1600_StatePermute_fu_288_ap_return_3;
    end else begin
        ap_return_3 = ap_return_3_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
        ap_return_4 = grp_KeccakF1600_StatePermute_fu_288_ap_return_4;
    end else begin
        ap_return_4 = ap_return_4_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
        ap_return_5 = grp_KeccakF1600_StatePermute_fu_288_ap_return_5;
    end else begin
        ap_return_5 = ap_return_5_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
        ap_return_6 = grp_KeccakF1600_StatePermute_fu_288_ap_return_6;
    end else begin
        ap_return_6 = ap_return_6_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
        ap_return_7 = grp_KeccakF1600_StatePermute_fu_288_ap_return_7;
    end else begin
        ap_return_7 = ap_return_7_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
        ap_return_8 = grp_KeccakF1600_StatePermute_fu_288_ap_return_8;
    end else begin
        ap_return_8 = ap_return_8_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
        ap_return_9 = grp_KeccakF1600_StatePermute_fu_288_ap_return_9;
    end else begin
        ap_return_9 = ap_return_9_preg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        k_kem_enc_s_key_blk_n = absorb_ret_absorb_fu_230_k_kem_dec_s_key_blk_n;
    end else begin
        k_kem_enc_s_key_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        k_kem_enc_s_key_read = absorb_ret_absorb_fu_230_k_kem_dec_s_key_read;
    end else begin
        k_kem_enc_s_key_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_KeccakF1600_StatePermute_fu_288_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (1'b0 == absorb_ret_absorb_fu_230_k_kem_dec_s_key_blk_n));
end

always @ (*) begin
    ap_block_state1_ignore_call53 = ((ap_start == 1'b0) | (1'b0 == absorb_ret_absorb_fu_230_k_kem_dec_s_key_blk_n));
end

assign grp_KeccakF1600_StatePermute_fu_288_ap_start = grp_KeccakF1600_StatePermute_fu_288_ap_start_reg;

endmodule //mlkem_accelerator_absorb_permute
